#!/bin/bash
# Usage: ./nmkvok $MAKE_ARGS
# Environment variables:
#   FILE: Which file to build all dependencies of. Default: "src/ShouldBuild.v".
#   FOLDER: Only .vok files in this folder will be built. Default: "src/".

if test -z "$FILE"; then
    FILE=src/ShouldBuild.v
fi

if test -z ${FOLDER+x}; then
    FOLDER=src/
fi

make $(make -n "$FILE"o | egrep '^echo "COQC '"$FOLDER" | sed -r 's/^.*"COQC (.*)"$/\1ok/') "$@"
