(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.golang.theory.
Require Export New.code.github_com.mit_pdos.gokv.vrsm.configservice.state_gk.

Set Default Proof Using "Type".

Module state_gk.
Module S.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : state_gk.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance S_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (state_gk.S.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Epoch" ∷ l.[(state_gk.S.t), "Epoch"] ↦{dq} v.(state_gk.S.Epoch') ∗
      "ReservedEpoch" ∷ l.[(state_gk.S.t), "ReservedEpoch"] ↦{dq} v.(state_gk.S.ReservedEpoch') ∗
      "LeaseExpiration" ∷ l.[(state_gk.S.t), "LeaseExpiration"] ↦{dq} v.(state_gk.S.LeaseExpiration') ∗
      "WantLeaseToExpire" ∷ l.[(state_gk.S.t), "WantLeaseToExpire"] ↦{dq} v.(state_gk.S.WantLeaseToExpire') ∗
      "Config" ∷ l.[(state_gk.S.t), "Config"] ↦{dq} v.(state_gk.S.Config') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance S_into_val_typed
   :
  IntoValTypedUnderlying (state_gk.S.t) (state_gk.Sⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance S_access_load_Epoch l (v : (state_gk.S.t)) dq :
  AccessStrict
    (l.[(state_gk.S.t), "Epoch"] ↦{dq} (v.(state_gk.S.Epoch')))
    (l.[(state_gk.S.t), "Epoch"] ↦{dq} (v.(state_gk.S.Epoch')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_Epoch l (v : (state_gk.S.t)) Epoch' :
  AccessStrict
    (l.[(state_gk.S.t), "Epoch"] ↦ (v.(state_gk.S.Epoch')))
    (l.[(state_gk.S.t), "Epoch"] ↦ Epoch')
    (l ↦ v) (l ↦ (v <|(state_gk.S.Epoch') := Epoch'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance S_access_load_ReservedEpoch l (v : (state_gk.S.t)) dq :
  AccessStrict
    (l.[(state_gk.S.t), "ReservedEpoch"] ↦{dq} (v.(state_gk.S.ReservedEpoch')))
    (l.[(state_gk.S.t), "ReservedEpoch"] ↦{dq} (v.(state_gk.S.ReservedEpoch')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_ReservedEpoch l (v : (state_gk.S.t)) ReservedEpoch' :
  AccessStrict
    (l.[(state_gk.S.t), "ReservedEpoch"] ↦ (v.(state_gk.S.ReservedEpoch')))
    (l.[(state_gk.S.t), "ReservedEpoch"] ↦ ReservedEpoch')
    (l ↦ v) (l ↦ (v <|(state_gk.S.ReservedEpoch') := ReservedEpoch'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance S_access_load_LeaseExpiration l (v : (state_gk.S.t)) dq :
  AccessStrict
    (l.[(state_gk.S.t), "LeaseExpiration"] ↦{dq} (v.(state_gk.S.LeaseExpiration')))
    (l.[(state_gk.S.t), "LeaseExpiration"] ↦{dq} (v.(state_gk.S.LeaseExpiration')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_LeaseExpiration l (v : (state_gk.S.t)) LeaseExpiration' :
  AccessStrict
    (l.[(state_gk.S.t), "LeaseExpiration"] ↦ (v.(state_gk.S.LeaseExpiration')))
    (l.[(state_gk.S.t), "LeaseExpiration"] ↦ LeaseExpiration')
    (l ↦ v) (l ↦ (v <|(state_gk.S.LeaseExpiration') := LeaseExpiration'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance S_access_load_WantLeaseToExpire l (v : (state_gk.S.t)) dq :
  AccessStrict
    (l.[(state_gk.S.t), "WantLeaseToExpire"] ↦{dq} (v.(state_gk.S.WantLeaseToExpire')))
    (l.[(state_gk.S.t), "WantLeaseToExpire"] ↦{dq} (v.(state_gk.S.WantLeaseToExpire')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_WantLeaseToExpire l (v : (state_gk.S.t)) WantLeaseToExpire' :
  AccessStrict
    (l.[(state_gk.S.t), "WantLeaseToExpire"] ↦ (v.(state_gk.S.WantLeaseToExpire')))
    (l.[(state_gk.S.t), "WantLeaseToExpire"] ↦ WantLeaseToExpire')
    (l ↦ v) (l ↦ (v <|(state_gk.S.WantLeaseToExpire') := WantLeaseToExpire'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance S_access_load_Config l (v : (state_gk.S.t)) dq :
  AccessStrict
    (l.[(state_gk.S.t), "Config"] ↦{dq} (v.(state_gk.S.Config')))
    (l.[(state_gk.S.t), "Config"] ↦{dq} (v.(state_gk.S.Config')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_Config l (v : (state_gk.S.t)) Config' :
  AccessStrict
    (l.[(state_gk.S.t), "Config"] ↦ (v.(state_gk.S.Config')))
    (l.[(state_gk.S.t), "Config"] ↦ Config')
    (l ↦ v) (l ↦ (v <|(state_gk.S.Config') := Config'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End S.

End state_gk.
