-- autogenerated from github.com/mit-pdos/perennial/goose/testdata/examples/comments
module

public import Perennial.Golang.Defn

@[expose] public section

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
noncomputable section

namespace pkg_id
def github_com.mit_pdos.perennial.goose.testdata.examples.comments : GoString := go!"github.com/mit-pdos/perennial/goose/testdata/examples/comments"
end pkg_id

namespace github_com.mit_pdos.perennial.goose.testdata.examples.comments

def Foo.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"github.com/mit-pdos/perennial/goose/testdata/examples/comments.Foo" [])

attribute [irreducible] Foo.ty

@[reducible] noncomputable def ONE [FfiSyntax] [GoGlobalContext] : val :=
  #(W64 1)

@[reducible] noncomputable def TWO [FfiSyntax] [GoGlobalContext] : val :=
  #(W64 2)

instance info' : PkgInfo pkg_id.github_com.mit_pdos.perennial.goose.testdata.examples.comments where
  pkgImportedPkgs := []

noncomputable def initialize' [FfiSyntax] [GoGlobalContext] : val :=
  (LamV BAnon
  (App (Val (package.init pkg_id.github_com.mit_pdos.perennial.goose.testdata.examples.comments)) (Lam BAnon
  (App (Val exceptionDo)
  (App (Val doExecute)
  (Val #()))))))

structure Foo [FfiSyntax] where
  mk ::
  a' : Bool

instance Foo.zero_val [FfiSyntax] : ZeroVal Foo :=
  ⟨Foo.mk zeroValDef⟩

@[reducible] def Foo.fieldsUnsealed [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  [(go.field_decl.FieldDecl go!"a" go.bool)]

@[irreducible] def Foo.fields [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  Foo.fieldsUnsealed

instance equals_unfold_Foo [FfiSyntax] [GoGlobalContext] :
    EqualsUnfold Foo.fields Foo.fieldsUnsealed :=
  ⟨by unfold Foo.fields; rfl⟩

@[reducible] def Foo.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.StructType Foo.fields)

class Foo.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying Foo.underlying Foo
  underlying : go.UnderlyingDirectedEq Foo.ty Foo.underlying
  get_a : ∀ (x : Foo), go.IsGoStepPureDetTagged under (StructFieldGet Foo.underlying go!"a") #x (Val #(x.a'))
  set_a : ∀ (x : Foo) (y : Bool), go.IsGoStepPureDetTagged under (StructFieldSet Foo.underlying go!"a") (PairV #x #y) (Val #(({ x with a' := y } : Foo)))

attribute [instance] Foo.TypeAssumptions.type_repr
  Foo.TypeAssumptions.underlying
  Foo.TypeAssumptions.get_a
  Foo.TypeAssumptions.set_a

class Assumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  Foo_instance : Foo.TypeAssumptions

attribute [instance] Assumptions.Foo_instance

end github_com.mit_pdos.perennial.goose.testdata.examples.comments

end
end Perennial
