-- autogenerated by goose proofgen; do not modify
import Perennial.Proof.ProofPrelude
import Perennial.GeneratedProof.github_com.mit_pdos.perennial.goose.testdata.examples.channel.lock
import Perennial.GeneratedProof.strings
import Perennial.GeneratedProof.time
import Perennial.Golang.Theory
import Perennial.Code.github_com.mit_pdos.perennial.goose.testdata.examples.channel

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
open Iris Iris.BI
noncomputable section
namespace github_com.mit_pdos.perennial.goose.testdata.examples.channel

namespace Cond
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Assumptions]

instance Cond_typed_pointsto :
    TypedPointsto (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond where
  typedPointstoDef l v dq := iprop(
    "L" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"L" l) v.L' dq ∗
    "waiters" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"waiters" l) v.waiters' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance Cond_into_val_typed :
    IntoValTypedUnderlying (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond.underlying := by
  solve_into_val_typed_struct

instance Cond_access_load_L (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"L" l) v.L' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"L" l) v.L' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Cond_access_store_L (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (L' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.lock.Lock) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"L" l) v.L' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"L" l) L' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with L' := L' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance Cond_access_load_waiters (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"waiters" l) v.waiters' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"waiters" l) v.waiters' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Cond_access_store_waiters (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (waiters' : GoSlice) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"waiters" l) v.waiters' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond go!"waiters" l) waiters' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with waiters' := waiters' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Cond) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end Cond

namespace Result
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Assumptions]

instance Result_typed_pointsto :
    TypedPointsto (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result where
  typedPointstoDef l v dq := iprop(
    "value" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"value" l) v.value' dq ∗
    "primary_won" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"primary_won" l) v.primary_won' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance Result_into_val_typed :
    IntoValTypedUnderlying (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result.underlying := by
  solve_into_val_typed_struct

instance Result_access_load_value (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"value" l) v.value' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"value" l) v.value' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Result_access_store_value (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (value' : GoString) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"value" l) v.value' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"value" l) value' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with value' := value' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance Result_access_load_primary_won (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"primary_won" l) v.primary_won' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"primary_won" l) v.primary_won' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Result_access_store_primary_won (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (primary_won' : Bool) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"primary_won" l) v.primary_won' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result go!"primary_won" l) primary_won' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with primary_won' := primary_won' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Result) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end Result

namespace request
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Assumptions]

instance request_typed_pointsto :
    TypedPointsto (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.request where
  typedPointstoDef l v dq := iprop(
    "f" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"f" l) v.f' dq ∗
    "result" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"result" l) v.result' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance request_into_val_typed :
    IntoValTypedUnderlying (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.request github_com.mit_pdos.perennial.goose.testdata.examples.channel.request.underlying := by
  solve_into_val_typed_struct

instance request_access_load_f (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"f" l) v.f' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"f" l) v.f' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance request_access_store_f (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (f' : GoFunc) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"f" l) v.f' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"f" l) f' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with f' := f' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance request_access_load_result (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"result" l) v.result' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"result" l) v.result' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance request_access_store_result (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (result' : GoChan) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"result" l) v.result' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.request go!"result" l) result' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with result' := result' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.request) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end request

namespace stream
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Assumptions]

instance stream_typed_pointsto :
    TypedPointsto (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream where
  typedPointstoDef l v dq := iprop(
    "req" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"req" l) v.req' dq ∗
    "res" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"res" l) v.res' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance stream_into_val_typed :
    IntoValTypedUnderlying (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream.underlying := by
  solve_into_val_typed_struct

instance stream_access_load_req (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"req" l) v.req' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"req" l) v.req' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance stream_access_store_req (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (req' : GoChan) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"req" l) v.req' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"req" l) req' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with req' := req' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance stream_access_load_res (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"res" l) v.res' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"res" l) v.res' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance stream_access_store_res (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (res' : GoChan) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"res" l) v.res' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream go!"res" l) res' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with res' := res' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.stream) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end stream

namespace streamold
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : github_com.mit_pdos.perennial.goose.testdata.examples.channel.Assumptions]

instance streamold_typed_pointsto :
    TypedPointsto (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold where
  typedPointstoDef l v dq := iprop(
    "req" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"req" l) v.req' dq ∗
    "res" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"res" l) v.res' dq ∗
    "f" ∷ typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"f" l) v.f' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance streamold_into_val_typed :
    IntoValTypedUnderlying (GF := GF) github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold.underlying := by
  solve_into_val_typed_struct

instance streamold_access_load_req (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"req" l) v.req' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"req" l) v.req' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance streamold_access_store_req (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (req' : GoChan) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"req" l) v.req' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"req" l) req' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with req' := req' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance streamold_access_load_res (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"res" l) v.res' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"res" l) v.res' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance streamold_access_store_res (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (res' : GoChan) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"res" l) v.res' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"res" l) res' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with res' := res' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance streamold_access_load_f (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"f" l) v.f' dq)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"f" l) v.f' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance streamold_access_store_f (l : Loc) (v : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (f' : GoFunc) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"f" l) v.f' (DFrac.own 1))
      (typedPointsto (structFieldRef github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold go!"f" l) f' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with f' := f' } : github_com.mit_pdos.perennial.goose.testdata.examples.channel.streamold) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end streamold

end github_com.mit_pdos.perennial.goose.testdata.examples.channel
end
end Perennial
