trusted = [
  "Listener",
  "Connection",
  "Address",
  "ConnectRet",
  "ReceiveRet",

  "Listen",
  "Connect",
  "Accept",
  "Send",
  "Receive",

  "FileRead",
  "FileWrite",
  "FileAppend",

  "GetTSC",
  "GetTimeRange",
]
