translate = [
  "!*",
  "Unwrap",
  "New",
  "AsType",
  "asType",
  "errorString*",
  "ErrUnsupported",
]
imports = ["!*"]

# translate the definitions of all type declarations goose supports
translate_types = true
