translate = [
  "Reader",
  "Writer",
  "ReaderFrom",
  "WriterTo",
  "StringWriter",
  "Err*",
  "err*",
  "EOF",
  "Discard",
  "discard",
  "multiReader",
  "multiWriter",
  "_",
]

# translate the definitions of all type declarations goose supports
translate_types = true
