translate = ["!*"]

imports = ["!*", "internal/runtime/atomic", "internal/runtime/sys"]

trusted = ["Gosched"]

# translate the definitions of all type declarations goose supports
translate_types = true
