translate = [
  "rngMax",
  "rngMask",

  "runtimeSource",
  "runtimeSource.Int63",

  "Rand",
  "Rand.Int63",
  "Rand.Int31",
  "Rand.Intn",
  "Rand.Int63n",
  "Rand.Int31n",

  "Intn",

  "ke", "we", "fe", "ke", "wn", "fn", "randautoseed", "randseednop", "rngCooked"
]

trusted = [
  "runtime_rand",
]

imports = ["sync", "internal/godebug", "sync/atomic"]
