(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.golang.theory.
Require Export New.code.github_com.mit_pdos.gokv.vrsm.replica.increasecommitargs_gk.

Set Default Proof Using "Type".

Module increasecommitargs_gk.
Module S.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : increasecommitargs_gk.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance S_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (increasecommitargs_gk.S.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "V" ∷ l.[(increasecommitargs_gk.S.t), "V"] ↦{dq} v.(increasecommitargs_gk.S.V') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance S_into_val_typed
   :
  IntoValTypedUnderlying (increasecommitargs_gk.S.t) (increasecommitargs_gk.Sⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance S_access_load_V l (v : (increasecommitargs_gk.S.t)) dq :
  AccessStrict
    (l.[(increasecommitargs_gk.S.t), "V"] ↦{dq} (v.(increasecommitargs_gk.S.V')))
    (l.[(increasecommitargs_gk.S.t), "V"] ↦{dq} (v.(increasecommitargs_gk.S.V')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S_access_store_V l (v : (increasecommitargs_gk.S.t)) V' :
  AccessStrict
    (l.[(increasecommitargs_gk.S.t), "V"] ↦ (v.(increasecommitargs_gk.S.V')))
    (l.[(increasecommitargs_gk.S.t), "V"] ↦ V')
    (l ↦ v) (l ↦ (v <|(increasecommitargs_gk.S.V') := V'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End S.

End increasecommitargs_gk.
