#!/bin/bash
# Usage: ./etc/mkvok $MAKE_ARGS
# Environment variables:
#   FILE: Which file to build all dependencies of. Default: "src/ShouldBuild.v".
#   FOLDER: Only .vok files in this folder will be built. Default: "src/".

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR/.."

if test -z "$FILE"; then
    FILE=src/ShouldBuild.v
fi

#if test -z ${FOLDER+x}; then
if test -z "$FOLDER"; then
    FOLDER=src/
fi

FILES=$(make -n "$FILE"o | egrep '^echo "COQC '"$FOLDER" | sed -E 's/^.*"COQC (.*)"$/\1ok/')
if test -z "$FILES"; then
    echo "Nothing found to build in $FOLDER"
    exit 1
fi

make $FILES "$@"
