-- autogenerated by goose proofgen; do not modify
import Perennial.Proof.ProofPrelude
import Perennial.Golang.Theory
import Perennial.Code.sort

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
open Iris Iris.BI
noncomputable section
namespace sort

namespace Interface
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance Interface_typed_pointsto :
    TypedPointsto (GF := GF) sort.Interface.t :=
  sorry -- Rocq: Admitted

instance Interface_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.Interface.t sort.«Interfaceⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end Interface

namespace lessSwap
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance lessSwap_typed_pointsto :
    TypedPointsto (GF := GF) sort.lessSwap.t :=
  sorry -- Rocq: Admitted

instance lessSwap_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.lessSwap.t sort.«lessSwapⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end lessSwap

namespace reverse
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance reverse_typed_pointsto :
    TypedPointsto (GF := GF) sort.reverse.t :=
  sorry -- Rocq: Admitted

instance reverse_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.reverse.t sort.«reverseⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end reverse

namespace IntSlice
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance IntSlice_typed_pointsto :
    TypedPointsto (GF := GF) sort.IntSlice.t :=
  sorry -- Rocq: Admitted

instance IntSlice_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.IntSlice.t sort.«IntSliceⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end IntSlice

namespace Float64Slice
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance Float64Slice_typed_pointsto :
    TypedPointsto (GF := GF) sort.Float64Slice.t :=
  sorry -- Rocq: Admitted

instance Float64Slice_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.Float64Slice.t sort.«Float64Sliceⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end Float64Slice

namespace StringSlice
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : sort.Assumptions]

instance StringSlice_typed_pointsto :
    TypedPointsto (GF := GF) sort.StringSlice.t :=
  sorry -- Rocq: Admitted

instance StringSlice_into_val_typed :
    IntoValTypedUnderlying (GF := GF) sort.StringSlice.t sort.«StringSliceⁱᵐᵖˡ» :=
  sorry -- Rocq: Admitted

end def_
end StringSlice

end sort
end
end Perennial
