(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.manualproof.github_com.mit_pdos.gokv.trusted_proph.
Require Export New.generatedproof.github_com.goose_lang.primitive.
Require Export New.golang.theory.

Require Export New.code.github_com.mit_pdos.gokv.trusted_proph.

Set Default Proof Using "Type".

Module trusted_proph.

(* type trusted_proph.ProphId *)
Module ProphId.
Section def.
Context `{ffi_syntax}.
Definition t := loc.
End def.
End ProphId.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext} `{!is_pkg_defined trusted_proph}.

Global Instance wp_func_call_NewProph :
  WpFuncCall trusted_proph.NewProph _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_ResolveBytes :
  WpFuncCall trusted_proph.ResolveBytes _ :=
  ltac:(solve_wp_func_call).

End names.
End trusted_proph.
