(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.primitive.
Require Export New.golang.theory.

Require Export New.code.github_com.goose_lang.std.std_core.

Set Default Proof Using "Type".

Module std_core.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext} `{!is_pkg_defined std_core}.

Global Instance wp_func_call_SumNoOverflow :
  WpFuncCall std_core.SumNoOverflow _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_SumAssumeNoOverflow :
  WpFuncCall std_core.SumAssumeNoOverflow _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MulNoOverflow :
  WpFuncCall std_core.MulNoOverflow _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MulAssumeNoOverflow :
  WpFuncCall std_core.MulAssumeNoOverflow _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_Shuffle :
  WpFuncCall std_core.Shuffle _ :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_Permutation :
  WpFuncCall std_core.Permutation _ :=
  ltac:(solve_wp_func_call).

End names.
End std_core.
