(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.errors.
Require Export New.generatedproof.io.
Require Export New.generatedproof.math.
Require Export New.generatedproof.slices.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.encoding.binary.

Set Default Proof Using "Type".

Module binary.
Module ByteOrder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ByteOrder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.ByteOrder.t). Admitted.

#[global] Instance ByteOrder_into_val_typed
   :
  IntoValTypedUnderlying (binary.ByteOrder.t) (binary.ByteOrderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ByteOrder.

Module AppendByteOrder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance AppendByteOrder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.AppendByteOrder.t). Admitted.

#[global] Instance AppendByteOrder_into_val_typed
   :
  IntoValTypedUnderlying (binary.AppendByteOrder.t) (binary.AppendByteOrderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End AppendByteOrder.

Module littleEndian.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance littleEndian_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.littleEndian.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance littleEndian_into_val_typed
   :
  IntoValTypedUnderlying (binary.littleEndian.t) (binary.littleEndianⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.

End def.
End littleEndian.

Module bigEndian.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance bigEndian_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.bigEndian.t). Admitted.

#[global] Instance bigEndian_into_val_typed
   :
  IntoValTypedUnderlying (binary.bigEndian.t) (binary.bigEndianⁱᵐᵖˡ).
Proof. Admitted.

End def.
End bigEndian.

Module coder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance coder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.coder.t). Admitted.

#[global] Instance coder_into_val_typed
   :
  IntoValTypedUnderlying (binary.coder.t) (binary.coderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End coder.

Module decoder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance decoder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.decoder.t). Admitted.

#[global] Instance decoder_into_val_typed
   :
  IntoValTypedUnderlying (binary.decoder.t) (binary.decoderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End decoder.

Module encoder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance encoder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.encoder.t). Admitted.

#[global] Instance encoder_into_val_typed
   :
  IntoValTypedUnderlying (binary.encoder.t) (binary.encoderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End encoder.

Module nativeEndian.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : binary.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance nativeEndian_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (binary.nativeEndian.t). Admitted.

#[global] Instance nativeEndian_into_val_typed
   :
  IntoValTypedUnderlying (binary.nativeEndian.t) (binary.nativeEndianⁱᵐᵖˡ).
Proof. Admitted.

End def.
End nativeEndian.

End binary.
