-- autogenerated from go.etcd.io/etcd/server/v3/storage/schema
import Perennial.Code.go_etcd_io.etcd.server.v3.storage.backend
import Perennial.Code.go_etcd_io.etcd.api.v3.etcdserverpb
import Perennial.Golang.Defn

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
noncomputable section

namespace pkg_id
def go_etcd_io.etcd.server.v3.storage.schema : GoString := go!"go.etcd.io/etcd/server/v3/storage/schema"
end pkg_id

namespace go_etcd_io.etcd.server.v3.storage.schema

def action.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.action" [])

attribute [irreducible] action.ty

def setKeyAction.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.setKeyAction" [])

attribute [irreducible] setKeyAction.ty

def deleteKeyAction.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.deleteKeyAction" [])

attribute [irreducible] deleteKeyAction.ty

def ActionList.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.ActionList" [])

attribute [irreducible] ActionList.ty

def AlarmBackend.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.AlarmBackend" [])

attribute [irreducible] AlarmBackend.ty

def alarmBackend.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.alarmBackend" [])

attribute [irreducible] alarmBackend.ty

def authBackend.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.authBackend" [])

attribute [irreducible] authBackend.ty

def authReadTx.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.authReadTx" [])

attribute [irreducible] authReadTx.ty

def authBatchTx.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.authBatchTx" [])

attribute [irreducible] authBatchTx.ty

def bucket.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.bucket" [])

attribute [irreducible] bucket.ty

def schemaChange.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.schemaChange" [])

attribute [irreducible] schemaChange.ty

def simpleSchemaChange.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.simpleSchemaChange" [])

attribute [irreducible] simpleSchemaChange.ty

def membershipBackend.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.membershipBackend" [])

attribute [irreducible] membershipBackend.ty

def migrationPlan.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.migrationPlan" [])

attribute [irreducible] migrationPlan.ty

def migrationStep.ty [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.Named go!"go.etcd.io/etcd/server/v3/storage/schema.migrationStep" [])

attribute [irreducible] migrationStep.ty

axiom alarmBackend.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom authBackend.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom authReadTx.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom authBatchTx.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom membershipBackend.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom migrationStep.underlying [FfiSyntax] [GoGlobalContext] : go.GoType

axiom revBytesLen [FfiSyntax] [GoGlobalContext] : val

axiom MemberAttributesSuffix [FfiSyntax] [GoGlobalContext] : val

axiom MemberRaftAttributesSuffix [FfiSyntax] [GoGlobalContext] : val

noncomputable def authEnabled [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.authEnabled"

axiom authEnabled.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def authDisabled [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.authDisabled"

axiom authDisabled.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def keyBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.keyBucketName"

axiom keyBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def metaBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.metaBucketName"

axiom metaBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def leaseBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.leaseBucketName"

axiom leaseBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def alarmBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.alarmBucketName"

axiom alarmBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def clusterBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.clusterBucketName"

axiom clusterBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def membersBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.membersBucketName"

axiom membersBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def membersRemovedBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.membersRemovedBucketName"

axiom membersRemovedBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def authBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.authBucketName"

axiom authBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def authUsersBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.authUsersBucketName"

axiom authUsersBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def authRolesBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.authRolesBucketName"

axiom authRolesBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def testBucketName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.testBucketName"

axiom testBucketName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Key [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Key"

axiom Key.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Meta [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Meta"

axiom Meta.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Lease [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Lease"

axiom Lease.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Alarm [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Alarm"

axiom Alarm.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Cluster [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Cluster"

axiom Cluster.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Members [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Members"

axiom Members.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def MembersRemoved [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MembersRemoved"

axiom MembersRemoved.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Auth [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Auth"

axiom Auth.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def AuthUsers [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.AuthUsers"

axiom AuthUsers.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def AuthRoles [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.AuthRoles"

axiom AuthRoles.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def Test [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Test"

axiom Test.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def AllBuckets [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.AllBuckets"

axiom AllBuckets.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def ScheduledCompactKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ScheduledCompactKeyName"

axiom ScheduledCompactKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def FinishedCompactKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.FinishedCompactKeyName"

axiom FinishedCompactKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def MetaConsistentIndexKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MetaConsistentIndexKeyName"

axiom MetaConsistentIndexKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def AuthEnabledKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.AuthEnabledKeyName"

axiom AuthEnabledKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def AuthRevisionKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.AuthRevisionKeyName"

axiom AuthRevisionKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def MetaTermKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MetaTermKeyName"

axiom MetaTermKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def MetaConfStateName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MetaConfStateName"

axiom MetaConfStateName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def ClusterClusterVersionKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ClusterClusterVersionKeyName"

axiom ClusterClusterVersionKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def ClusterDowngradeKeyName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ClusterDowngradeKeyName"

axiom ClusterDowngradeKeyName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def MetaStorageVersionName [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MetaStorageVersionName"

axiom MetaStorageVersionName.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def schemaChanges [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.schemaChanges"

axiom schemaChanges.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def emptyStorageVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.emptyStorageVersion"

axiom emptyStorageVersion.init [FfiSyntax] [GoGlobalContext] : val

noncomputable def restoreFieldValueAction [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.restoreFieldValueAction"

noncomputable def NewAlarmBackend [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.NewAlarmBackend"

noncomputable def NewAuthBackend [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.NewAuthBackend"

noncomputable def unsafeReadAuthEnabled [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeReadAuthEnabled"

noncomputable def unsafeReadAuthRevision [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeReadAuthRevision"

noncomputable def UnsafeCreateAuthRolesBucket [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeCreateAuthRolesBucket"

noncomputable def unsafeGetRole [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeGetRole"

noncomputable def unsafeGetAllRoles [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeGetAllRoles"

noncomputable def unsafeGetUser [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeGetUser"

noncomputable def unsafeGetAllUsers [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeGetAllUsers"

noncomputable def DefaultIgnores [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.DefaultIgnores"

noncomputable def BackendMemberKey [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.BackendMemberKey"

noncomputable def addNewField [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.addNewField"

noncomputable def UnsafeCreateMetaBucket [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeCreateMetaBucket"

noncomputable def CreateMetaBucket [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.CreateMetaBucket"

noncomputable def UnsafeReadConsistentIndex [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeReadConsistentIndex"

noncomputable def ReadConsistentIndex [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ReadConsistentIndex"

noncomputable def UnsafeUpdateConsistentIndexForce [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeUpdateConsistentIndexForce"

noncomputable def UnsafeUpdateConsistentIndex [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeUpdateConsistentIndex"

noncomputable def unsafeUpdateConsistentIndex [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeUpdateConsistentIndex"

noncomputable def MustUnsafeSaveConfStateToBackend [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MustUnsafeSaveConfStateToBackend"

noncomputable def UnsafeConfStateFromBackend [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeConfStateFromBackend"

noncomputable def UnsafeCreateLeaseBucket [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeCreateLeaseBucket"

noncomputable def MustUnsafeGetAllLeases [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MustUnsafeGetAllLeases"

noncomputable def MustUnsafePutLease [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MustUnsafePutLease"

noncomputable def UnsafeDeleteLease [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeDeleteLease"

noncomputable def MustUnsafeGetLease [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.MustUnsafeGetLease"

noncomputable def leaseIDToBytes [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.leaseIDToBytes"

noncomputable def bytesToLeaseID [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.bytesToLeaseID"

noncomputable def NewMembershipBackend [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.NewMembershipBackend"

noncomputable def mustParseMemberIDFromBytes [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.mustParseMemberIDFromBytes"

noncomputable def newPlan [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.newPlan"

noncomputable def newMigrationStep [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.newMigrationStep"

noncomputable def trimToMinor [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.trimToMinor"

noncomputable def Validate [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Validate"

noncomputable def unsafeValidate [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.unsafeValidate"

noncomputable def localBinaryVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.localBinaryVersion"

noncomputable def Migrate [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.Migrate"

noncomputable def UnsafeMigrate [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeMigrate"

noncomputable def DetectSchemaVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.DetectSchemaVersion"

noncomputable def UnsafeDetectSchemaVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeDetectSchemaVersion"

noncomputable def schemaChangesForVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.schemaChangesForVersion"

noncomputable def ReadStorageVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ReadStorageVersion"

noncomputable def UnsafeReadStorageVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeReadStorageVersion"

noncomputable def ReadStorageVersionFromSnapshot [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.ReadStorageVersionFromSnapshot"

noncomputable def UnsafeSetStorageVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeSetStorageVersion"

noncomputable def UnsafeClearStorageVersion [FfiSyntax] [GoGlobalContext] : GoString :=
  go!"go.etcd.io/etcd/server/v3/storage/schema.UnsafeClearStorageVersion"

instance info' : PkgInfo pkg_id.go_etcd_io.etcd.server.v3.storage.schema where
  pkgImportedPkgs := [pkg_id.go_etcd_io.etcd.server.v3.storage.backend, pkg_id.go_etcd_io.etcd.api.v3.etcdserverpb]

axiom «_».init [FfiSyntax] [GoGlobalContext] : val

noncomputable def initialize' [FfiSyntax] [GoGlobalContext] : val :=
  (LamV BAnon
  (App (Val (package.init pkg_id.go_etcd_io.etcd.server.v3.storage.schema)) (Lam BAnon
  (App (Val exceptionDo)
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (App (Val exceptionSeq) (Lam BAnon
  (App (Val doExecute)
  (App (Val schemaChanges.init) (Val #())))))
  (App (Val doExecute)
  (App (Val emptyStorageVersion.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val MetaStorageVersionName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val ClusterDowngradeKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val ClusterClusterVersionKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val MetaConfStateName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val MetaTermKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val AuthRevisionKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val AuthEnabledKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val MetaConsistentIndexKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val FinishedCompactKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val ScheduledCompactKeyName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val AllBuckets.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Test.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val AuthRoles.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val AuthUsers.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Auth.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val MembersRemoved.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Members.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Cluster.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Alarm.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Lease.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Meta.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val Key.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val testBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val authRolesBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val authUsersBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val authBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val membersRemovedBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val membersBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val clusterBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val alarmBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val leaseBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val metaBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val keyBucketName.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val «_».init) (Val #()))))))
  (App (Val doExecute)
  (App (Val «_».init) (Val #()))))))
  (App (Val doExecute)
  (App (Val «_».init) (Val #()))))))
  (App (Val doExecute)
  (App (Val authDisabled.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val authEnabled.init) (Val #()))))))
  (App (Val doExecute)
  (App (Val _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.initialize') (Val #()))))))
  (App (Val doExecute)
  (App (Val _root_.Perennial.go_etcd_io.etcd.api.v3.etcdserverpb.initialize') (Val #()))))))))

abbrev action [FfiSyntax] : Type := GoInterface

@[reducible] def action.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.InterfaceType [(go.InterfaceElem.MethodElem go!"unsafeDo" (go.signature.Signature [_root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.UnsafeReadWriter.ty] false [action.ty, go.error]))])

class action.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  underlying : go.UnderlyingDirectedEq action.ty action.underlying

attribute [instance] action.TypeAssumptions.underlying

structure setKeyAction [FfiSyntax] where
  mk ::
  Bucket' : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket
  FieldName' : GoSlice
  FieldValue' : GoSlice

instance setKeyAction.zero_val [FfiSyntax] : ZeroVal setKeyAction :=
  ⟨setKeyAction.mk zeroValDef zeroValDef zeroValDef⟩

@[reducible] def setKeyAction.fieldsUnsealed [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  [(go.field_decl.FieldDecl go!"Bucket" _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket.ty),
(go.field_decl.FieldDecl go!"FieldName" (go.GoType.SliceType go.byte)),
(go.field_decl.FieldDecl go!"FieldValue" (go.GoType.SliceType go.byte))]

@[irreducible] def setKeyAction.fields [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  setKeyAction.fieldsUnsealed

instance equals_unfold_setKeyAction [FfiSyntax] [GoGlobalContext] :
    EqualsUnfold setKeyAction.fields setKeyAction.fieldsUnsealed :=
  ⟨by unfold setKeyAction.fields; rfl⟩

@[reducible] def setKeyAction.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.StructType setKeyAction.fields)

class setKeyAction.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying setKeyAction.underlying setKeyAction
  underlying : go.UnderlyingDirectedEq setKeyAction.ty setKeyAction.underlying
  get_Bucket : ∀ (x : setKeyAction), go.IsGoStepPureDetTagged under (StructFieldGet setKeyAction.underlying go!"Bucket") #x (Val #(x.Bucket'))
  set_Bucket : ∀ (x : setKeyAction) (y : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket), go.IsGoStepPureDetTagged under (StructFieldSet setKeyAction.underlying go!"Bucket") (PairV #x #y) (Val #(({ x with Bucket' := y } : setKeyAction)))
  get_FieldName : ∀ (x : setKeyAction), go.IsGoStepPureDetTagged under (StructFieldGet setKeyAction.underlying go!"FieldName") #x (Val #(x.FieldName'))
  set_FieldName : ∀ (x : setKeyAction) (y : GoSlice), go.IsGoStepPureDetTagged under (StructFieldSet setKeyAction.underlying go!"FieldName") (PairV #x #y) (Val #(({ x with FieldName' := y } : setKeyAction)))
  get_FieldValue : ∀ (x : setKeyAction), go.IsGoStepPureDetTagged under (StructFieldGet setKeyAction.underlying go!"FieldValue") #x (Val #(x.FieldValue'))
  set_FieldValue : ∀ (x : setKeyAction) (y : GoSlice), go.IsGoStepPureDetTagged under (StructFieldSet setKeyAction.underlying go!"FieldValue") (PairV #x #y) (Val #(({ x with FieldValue' := y } : setKeyAction)))

attribute [instance] setKeyAction.TypeAssumptions.type_repr
  setKeyAction.TypeAssumptions.underlying
  setKeyAction.TypeAssumptions.get_Bucket
  setKeyAction.TypeAssumptions.set_Bucket
  setKeyAction.TypeAssumptions.get_FieldName
  setKeyAction.TypeAssumptions.set_FieldName
  setKeyAction.TypeAssumptions.get_FieldValue
  setKeyAction.TypeAssumptions.set_FieldValue

structure deleteKeyAction [FfiSyntax] where
  mk ::
  Bucket' : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket
  FieldName' : GoSlice

instance deleteKeyAction.zero_val [FfiSyntax] : ZeroVal deleteKeyAction :=
  ⟨deleteKeyAction.mk zeroValDef zeroValDef⟩

@[reducible] def deleteKeyAction.fieldsUnsealed [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  [(go.field_decl.FieldDecl go!"Bucket" _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket.ty),
(go.field_decl.FieldDecl go!"FieldName" (go.GoType.SliceType go.byte))]

@[irreducible] def deleteKeyAction.fields [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  deleteKeyAction.fieldsUnsealed

instance equals_unfold_deleteKeyAction [FfiSyntax] [GoGlobalContext] :
    EqualsUnfold deleteKeyAction.fields deleteKeyAction.fieldsUnsealed :=
  ⟨by unfold deleteKeyAction.fields; rfl⟩

@[reducible] def deleteKeyAction.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.StructType deleteKeyAction.fields)

class deleteKeyAction.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying deleteKeyAction.underlying deleteKeyAction
  underlying : go.UnderlyingDirectedEq deleteKeyAction.ty deleteKeyAction.underlying
  get_Bucket : ∀ (x : deleteKeyAction), go.IsGoStepPureDetTagged under (StructFieldGet deleteKeyAction.underlying go!"Bucket") #x (Val #(x.Bucket'))
  set_Bucket : ∀ (x : deleteKeyAction) (y : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Bucket), go.IsGoStepPureDetTagged under (StructFieldSet deleteKeyAction.underlying go!"Bucket") (PairV #x #y) (Val #(({ x with Bucket' := y } : deleteKeyAction)))
  get_FieldName : ∀ (x : deleteKeyAction), go.IsGoStepPureDetTagged under (StructFieldGet deleteKeyAction.underlying go!"FieldName") #x (Val #(x.FieldName'))
  set_FieldName : ∀ (x : deleteKeyAction) (y : GoSlice), go.IsGoStepPureDetTagged under (StructFieldSet deleteKeyAction.underlying go!"FieldName") (PairV #x #y) (Val #(({ x with FieldName' := y } : deleteKeyAction)))

attribute [instance] deleteKeyAction.TypeAssumptions.type_repr
  deleteKeyAction.TypeAssumptions.underlying
  deleteKeyAction.TypeAssumptions.get_Bucket
  deleteKeyAction.TypeAssumptions.set_Bucket
  deleteKeyAction.TypeAssumptions.get_FieldName
  deleteKeyAction.TypeAssumptions.set_FieldName

abbrev ActionList [FfiSyntax] : Type := GoSlice

@[reducible] def ActionList.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.SliceType action.ty)

class ActionList.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  underlying : go.UnderlyingDirectedEq ActionList.ty ActionList.underlying

attribute [instance] ActionList.TypeAssumptions.underlying

abbrev AlarmBackend [FfiSyntax] : Type := GoInterface

@[reducible] def AlarmBackend.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.InterfaceType [(go.InterfaceElem.MethodElem go!"CreateAlarmBucket" (go.signature.Signature [] false [])), (go.InterfaceElem.MethodElem go!"ForceCommit" (go.signature.Signature [] false [])), (go.InterfaceElem.MethodElem go!"GetAllAlarms" (go.signature.Signature [] false [(go.GoType.SliceType (go.GoType.PointerType _root_.Perennial.go_etcd_io.etcd.api.v3.etcdserverpb.AlarmMember.ty)), go.error])), (go.InterfaceElem.MethodElem go!"MustDeleteAlarm" (go.signature.Signature [(go.GoType.PointerType _root_.Perennial.go_etcd_io.etcd.api.v3.etcdserverpb.AlarmMember.ty)] false [])), (go.InterfaceElem.MethodElem go!"MustPutAlarm" (go.signature.Signature [(go.GoType.PointerType _root_.Perennial.go_etcd_io.etcd.api.v3.etcdserverpb.AlarmMember.ty)] false []))])

class AlarmBackend.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  underlying : go.UnderlyingDirectedEq AlarmBackend.ty AlarmBackend.underlying

attribute [instance] AlarmBackend.TypeAssumptions.underlying

axiom alarmBackend : Type
axiom alarmBackend.zero_val : ZeroVal alarmBackend
attribute [instance] alarmBackend.zero_val

class alarmBackend.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying alarmBackend.underlying alarmBackend
  underlying : go.UnderlyingDirectedEq alarmBackend.ty alarmBackend.underlying
  isUnderlying : go.IsUnderlying alarmBackend.underlying alarmBackend.underlying

attribute [instance] alarmBackend.TypeAssumptions.type_repr
  alarmBackend.TypeAssumptions.underlying
  alarmBackend.TypeAssumptions.isUnderlying

axiom authBackend : Type
axiom authBackend.zero_val : ZeroVal authBackend
attribute [instance] authBackend.zero_val

class authBackend.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying authBackend.underlying authBackend
  underlying : go.UnderlyingDirectedEq authBackend.ty authBackend.underlying
  isUnderlying : go.IsUnderlying authBackend.underlying authBackend.underlying

attribute [instance] authBackend.TypeAssumptions.type_repr
  authBackend.TypeAssumptions.underlying
  authBackend.TypeAssumptions.isUnderlying

axiom authReadTx : Type
axiom authReadTx.zero_val : ZeroVal authReadTx
attribute [instance] authReadTx.zero_val

class authReadTx.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying authReadTx.underlying authReadTx
  underlying : go.UnderlyingDirectedEq authReadTx.ty authReadTx.underlying
  isUnderlying : go.IsUnderlying authReadTx.underlying authReadTx.underlying

attribute [instance] authReadTx.TypeAssumptions.type_repr
  authReadTx.TypeAssumptions.underlying
  authReadTx.TypeAssumptions.isUnderlying

axiom authBatchTx : Type
axiom authBatchTx.zero_val : ZeroVal authBatchTx
attribute [instance] authBatchTx.zero_val

class authBatchTx.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying authBatchTx.underlying authBatchTx
  underlying : go.UnderlyingDirectedEq authBatchTx.ty authBatchTx.underlying
  isUnderlying : go.IsUnderlying authBatchTx.underlying authBatchTx.underlying

attribute [instance] authBatchTx.TypeAssumptions.type_repr
  authBatchTx.TypeAssumptions.underlying
  authBatchTx.TypeAssumptions.isUnderlying

structure bucket [FfiSyntax] where
  mk ::
  id' : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.BucketID
  name' : GoSlice
  safeRangeBucket' : Bool

instance bucket.zero_val [FfiSyntax] : ZeroVal bucket :=
  ⟨bucket.mk zeroValDef zeroValDef zeroValDef⟩

@[reducible] def bucket.fieldsUnsealed [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  [(go.field_decl.FieldDecl go!"id" _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.BucketID.ty),
(go.field_decl.FieldDecl go!"name" (go.GoType.SliceType go.byte)),
(go.field_decl.FieldDecl go!"safeRangeBucket" go.bool)]

@[irreducible] def bucket.fields [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  bucket.fieldsUnsealed

instance equals_unfold_bucket [FfiSyntax] [GoGlobalContext] :
    EqualsUnfold bucket.fields bucket.fieldsUnsealed :=
  ⟨by unfold bucket.fields; rfl⟩

@[reducible] def bucket.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.StructType bucket.fields)

class bucket.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying bucket.underlying bucket
  underlying : go.UnderlyingDirectedEq bucket.ty bucket.underlying
  get_id : ∀ (x : bucket), go.IsGoStepPureDetTagged under (StructFieldGet bucket.underlying go!"id") #x (Val #(x.id'))
  set_id : ∀ (x : bucket) (y : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.BucketID), go.IsGoStepPureDetTagged under (StructFieldSet bucket.underlying go!"id") (PairV #x #y) (Val #(({ x with id' := y } : bucket)))
  get_name : ∀ (x : bucket), go.IsGoStepPureDetTagged under (StructFieldGet bucket.underlying go!"name") #x (Val #(x.name'))
  set_name : ∀ (x : bucket) (y : GoSlice), go.IsGoStepPureDetTagged under (StructFieldSet bucket.underlying go!"name") (PairV #x #y) (Val #(({ x with name' := y } : bucket)))
  get_safeRangeBucket : ∀ (x : bucket), go.IsGoStepPureDetTagged under (StructFieldGet bucket.underlying go!"safeRangeBucket") #x (Val #(x.safeRangeBucket'))
  set_safeRangeBucket : ∀ (x : bucket) (y : Bool), go.IsGoStepPureDetTagged under (StructFieldSet bucket.underlying go!"safeRangeBucket") (PairV #x #y) (Val #(({ x with safeRangeBucket' := y } : bucket)))

attribute [instance] bucket.TypeAssumptions.type_repr
  bucket.TypeAssumptions.underlying
  bucket.TypeAssumptions.get_id
  bucket.TypeAssumptions.set_id
  bucket.TypeAssumptions.get_name
  bucket.TypeAssumptions.set_name
  bucket.TypeAssumptions.get_safeRangeBucket
  bucket.TypeAssumptions.set_safeRangeBucket

abbrev schemaChange [FfiSyntax] : Type := GoInterface

@[reducible] def schemaChange.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.InterfaceType [(go.InterfaceElem.MethodElem go!"downgradeAction" (go.signature.Signature [] false [action.ty])), (go.InterfaceElem.MethodElem go!"upgradeAction" (go.signature.Signature [] false [action.ty]))])

class schemaChange.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  underlying : go.UnderlyingDirectedEq schemaChange.ty schemaChange.underlying

attribute [instance] schemaChange.TypeAssumptions.underlying

structure simpleSchemaChange [FfiSyntax] where
  mk ::
  upgrade' : action
  downgrade' : action

instance simpleSchemaChange.zero_val [FfiSyntax] : ZeroVal simpleSchemaChange :=
  ⟨simpleSchemaChange.mk zeroValDef zeroValDef⟩

@[reducible] def simpleSchemaChange.fieldsUnsealed [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  [(go.field_decl.FieldDecl go!"upgrade" action.ty),
(go.field_decl.FieldDecl go!"downgrade" action.ty)]

@[irreducible] def simpleSchemaChange.fields [FfiSyntax] [GoGlobalContext] : List go.field_decl :=
  simpleSchemaChange.fieldsUnsealed

instance equals_unfold_simpleSchemaChange [FfiSyntax] [GoGlobalContext] :
    EqualsUnfold simpleSchemaChange.fields simpleSchemaChange.fieldsUnsealed :=
  ⟨by unfold simpleSchemaChange.fields; rfl⟩

@[reducible] def simpleSchemaChange.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.StructType simpleSchemaChange.fields)

class simpleSchemaChange.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying simpleSchemaChange.underlying simpleSchemaChange
  underlying : go.UnderlyingDirectedEq simpleSchemaChange.ty simpleSchemaChange.underlying
  get_upgrade : ∀ (x : simpleSchemaChange), go.IsGoStepPureDetTagged under (StructFieldGet simpleSchemaChange.underlying go!"upgrade") #x (Val #(x.upgrade'))
  set_upgrade : ∀ (x : simpleSchemaChange) (y : action), go.IsGoStepPureDetTagged under (StructFieldSet simpleSchemaChange.underlying go!"upgrade") (PairV #x #y) (Val #(({ x with upgrade' := y } : simpleSchemaChange)))
  get_downgrade : ∀ (x : simpleSchemaChange), go.IsGoStepPureDetTagged under (StructFieldGet simpleSchemaChange.underlying go!"downgrade") #x (Val #(x.downgrade'))
  set_downgrade : ∀ (x : simpleSchemaChange) (y : action), go.IsGoStepPureDetTagged under (StructFieldSet simpleSchemaChange.underlying go!"downgrade") (PairV #x #y) (Val #(({ x with downgrade' := y } : simpleSchemaChange)))

attribute [instance] simpleSchemaChange.TypeAssumptions.type_repr
  simpleSchemaChange.TypeAssumptions.underlying
  simpleSchemaChange.TypeAssumptions.get_upgrade
  simpleSchemaChange.TypeAssumptions.set_upgrade
  simpleSchemaChange.TypeAssumptions.get_downgrade
  simpleSchemaChange.TypeAssumptions.set_downgrade

axiom membershipBackend : Type
axiom membershipBackend.zero_val : ZeroVal membershipBackend
attribute [instance] membershipBackend.zero_val

class membershipBackend.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying membershipBackend.underlying membershipBackend
  underlying : go.UnderlyingDirectedEq membershipBackend.ty membershipBackend.underlying
  isUnderlying : go.IsUnderlying membershipBackend.underlying membershipBackend.underlying

attribute [instance] membershipBackend.TypeAssumptions.type_repr
  membershipBackend.TypeAssumptions.underlying
  membershipBackend.TypeAssumptions.isUnderlying

abbrev migrationPlan [FfiSyntax] : Type := GoSlice

@[reducible] def migrationPlan.underlying [FfiSyntax] [GoGlobalContext] : go.GoType :=
  (go.GoType.SliceType migrationStep.ty)

class migrationPlan.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  underlying : go.UnderlyingDirectedEq migrationPlan.ty migrationPlan.underlying

attribute [instance] migrationPlan.TypeAssumptions.underlying

axiom migrationStep : Type
axiom migrationStep.zero_val : ZeroVal migrationStep
attribute [instance] migrationStep.zero_val

class migrationStep.TypeAssumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  type_repr : go.TypeReprUnderlying migrationStep.underlying migrationStep
  underlying : go.UnderlyingDirectedEq migrationStep.ty migrationStep.underlying
  isUnderlying : go.IsUnderlying migrationStep.underlying migrationStep.underlying

attribute [instance] migrationStep.TypeAssumptions.type_repr
  migrationStep.TypeAssumptions.underlying
  migrationStep.TypeAssumptions.isUnderlying

class Assumptions [FfiSyntax] [GoGlobalContext] [GoLocalContext] [GoSemanticsFunctions] : Prop where
  action_instance : action.TypeAssumptions
  setKeyAction_instance : setKeyAction.TypeAssumptions
  deleteKeyAction_instance : deleteKeyAction.TypeAssumptions
  ActionList_instance : ActionList.TypeAssumptions
  AlarmBackend_instance : AlarmBackend.TypeAssumptions
  alarmBackend_instance : alarmBackend.TypeAssumptions
  authBackend_instance : authBackend.TypeAssumptions
  authReadTx_instance : authReadTx.TypeAssumptions
  authBatchTx_instance : authBatchTx.TypeAssumptions
  bucket_instance : bucket.TypeAssumptions
  schemaChange_instance : schemaChange.TypeAssumptions
  simpleSchemaChange_instance : simpleSchemaChange.TypeAssumptions
  membershipBackend_instance : membershipBackend.TypeAssumptions
  migrationPlan_instance : migrationPlan.TypeAssumptions
  migrationStep_instance : migrationStep.TypeAssumptions
  import_backend_Assumption : _root_.Perennial.go_etcd_io.etcd.server.v3.storage.backend.Assumptions
  import_etcdserverpb_Assumption : _root_.Perennial.go_etcd_io.etcd.api.v3.etcdserverpb.Assumptions

attribute [instance] Assumptions.action_instance
  Assumptions.setKeyAction_instance
  Assumptions.deleteKeyAction_instance
  Assumptions.ActionList_instance
  Assumptions.AlarmBackend_instance
  Assumptions.alarmBackend_instance
  Assumptions.authBackend_instance
  Assumptions.authReadTx_instance
  Assumptions.authBatchTx_instance
  Assumptions.bucket_instance
  Assumptions.schemaChange_instance
  Assumptions.simpleSchemaChange_instance
  Assumptions.membershipBackend_instance
  Assumptions.migrationPlan_instance
  Assumptions.migrationStep_instance
  Assumptions.import_backend_Assumption
  Assumptions.import_etcdserverpb_Assumption

end go_etcd_io.etcd.server.v3.storage.schema

end
end Perennial
