translate = [
  "Code",
  "Canceled",
  "DataLoss",
  "DeadlineExceeded",
  "FailedPrecondition",
  "InvalidArgument",
  "NotFound",
  "OutOfRange",
  "PermissionDenied",
  "ResourceExhausted",
  "Unauthenticated",
  "Unavailable",
]
imports = [
  "!*"
]
