(* autogenerated by goose proofgen (types); do not modify *)
From New.code Require Import testing.
From New.golang Require Import theory.

Axiom falso : False.

(* autogenerated by proofgen (names); do not modify *)
Require Import New.code.testing.
Require Export New.proof.proof_prelude.
Module testing.
Section defs.
Class GlobalAddrs :=
{
}.

Context `{!GlobalAddrs}.
Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!goGlobalsGS Σ}.

Definition var_addrs : list (go_string * loc) := [
  ].

Definition is_defined := is_global_definitions testing.pkg_name' var_addrs testing.functions' testing.msets'.

Definition own_allocated `{!GlobalAddrs} : iProp Σ :=
True.

Global Instance wp_func_call_AllocsPerRun : 
  WpFuncCall testing.pkg_name' "AllocsPerRun" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_initBenchmarkFlags : 
  WpFuncCall testing.pkg_name' "initBenchmarkFlags" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_prettyPrint : 
  WpFuncCall testing.pkg_name' "prettyPrint" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_benchmarkName : 
  WpFuncCall testing.pkg_name' "benchmarkName" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_RunBenchmarks : 
  WpFuncCall testing.pkg_name' "RunBenchmarks" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runBenchmarks : 
  WpFuncCall testing.pkg_name' "runBenchmarks" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Benchmark : 
  WpFuncCall testing.pkg_name' "Benchmark" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Coverage : 
  WpFuncCall testing.pkg_name' "Coverage" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_RegisterCover : 
  WpFuncCall testing.pkg_name' "RegisterCover" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_mustBeNil : 
  WpFuncCall testing.pkg_name' "mustBeNil" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_coverReport : 
  WpFuncCall testing.pkg_name' "coverReport" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_RunExamples : 
  WpFuncCall testing.pkg_name' "RunExamples" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runExamples : 
  WpFuncCall testing.pkg_name' "runExamples" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_sortLines : 
  WpFuncCall testing.pkg_name' "sortLines" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_initFuzzFlags : 
  WpFuncCall testing.pkg_name' "initFuzzFlags" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runFuzzTests : 
  WpFuncCall testing.pkg_name' "runFuzzTests" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runFuzzing : 
  WpFuncCall testing.pkg_name' "runFuzzing" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_fRunner : 
  WpFuncCall testing.pkg_name' "fRunner" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_allMatcher : 
  WpFuncCall testing.pkg_name' "allMatcher" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_newMatcher : 
  WpFuncCall testing.pkg_name' "newMatcher" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_splitRegexp : 
  WpFuncCall testing.pkg_name' "splitRegexp" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_parseSubtestNumber : 
  WpFuncCall testing.pkg_name' "parseSubtestNumber" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_rewrite : 
  WpFuncCall testing.pkg_name' "rewrite" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_isSpace : 
  WpFuncCall testing.pkg_name' "isSpace" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_registerCover2 : 
  WpFuncCall testing.pkg_name' "registerCover2" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_coverReport2 : 
  WpFuncCall testing.pkg_name' "coverReport2" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_coverage2 : 
  WpFuncCall testing.pkg_name' "coverage2" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runExample : 
  WpFuncCall testing.pkg_name' "runExample" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Init : 
  WpFuncCall testing.pkg_name' "Init" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_newChattyPrinter : 
  WpFuncCall testing.pkg_name' "newChattyPrinter" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Short : 
  WpFuncCall testing.pkg_name' "Short" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Testing : 
  WpFuncCall testing.pkg_name' "Testing" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_CoverMode : 
  WpFuncCall testing.pkg_name' "CoverMode" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Verbose : 
  WpFuncCall testing.pkg_name' "Verbose" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_fmtDuration : 
  WpFuncCall testing.pkg_name' "fmtDuration" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_removeAll : 
  WpFuncCall testing.pkg_name' "removeAll" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_callerName : 
  WpFuncCall testing.pkg_name' "callerName" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_pcToName : 
  WpFuncCall testing.pkg_name' "pcToName" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_tRunner : 
  WpFuncCall testing.pkg_name' "tRunner" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_newTestContext : 
  WpFuncCall testing.pkg_name' "newTestContext" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_Main : 
  WpFuncCall testing.pkg_name' "Main" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_MainStart : 
  WpFuncCall testing.pkg_name' "MainStart" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_listTests : 
  WpFuncCall testing.pkg_name' "listTests" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_RunTests : 
  WpFuncCall testing.pkg_name' "RunTests" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runTests : 
  WpFuncCall testing.pkg_name' "runTests" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_toOutputDir : 
  WpFuncCall testing.pkg_name' "toOutputDir" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_runningList : 
  WpFuncCall testing.pkg_name' "runningList" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_parseCpuList : 
  WpFuncCall testing.pkg_name' "parseCpuList" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_shouldFailFast : 
  WpFuncCall testing.pkg_name' "shouldFailFast" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_isWindowsRetryable : 
  WpFuncCall testing.pkg_name' "isWindowsRetryable" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_highPrecisionTimeNow : 
  WpFuncCall testing.pkg_name' "highPrecisionTimeNow" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_func_call_highPrecisionTimeSince : 
  WpFuncCall testing.pkg_name' "highPrecisionTimeSince" _ is_defined :=
  ltac:(apply wp_func_call'; reflexivity).

Global Instance wp_method_call_durationOrCountFlag'ptr_Set : 
  WpMethodCall testing.pkg_name' "durationOrCountFlag'ptr" "Set" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_durationOrCountFlag'ptr_String : 
  WpMethodCall testing.pkg_name' "durationOrCountFlag'ptr" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Cleanup : 
  WpMethodCall testing.pkg_name' "B'ptr" "Cleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Elapsed : 
  WpMethodCall testing.pkg_name' "B'ptr" "Elapsed" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Error : 
  WpMethodCall testing.pkg_name' "B'ptr" "Error" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Errorf : 
  WpMethodCall testing.pkg_name' "B'ptr" "Errorf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Fail : 
  WpMethodCall testing.pkg_name' "B'ptr" "Fail" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_FailNow : 
  WpMethodCall testing.pkg_name' "B'ptr" "FailNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Failed : 
  WpMethodCall testing.pkg_name' "B'ptr" "Failed" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Fatal : 
  WpMethodCall testing.pkg_name' "B'ptr" "Fatal" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Fatalf : 
  WpMethodCall testing.pkg_name' "B'ptr" "Fatalf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Helper : 
  WpMethodCall testing.pkg_name' "B'ptr" "Helper" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Log : 
  WpMethodCall testing.pkg_name' "B'ptr" "Log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Logf : 
  WpMethodCall testing.pkg_name' "B'ptr" "Logf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Name : 
  WpMethodCall testing.pkg_name' "B'ptr" "Name" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_ReportAllocs : 
  WpMethodCall testing.pkg_name' "B'ptr" "ReportAllocs" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_ReportMetric : 
  WpMethodCall testing.pkg_name' "B'ptr" "ReportMetric" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_ResetTimer : 
  WpMethodCall testing.pkg_name' "B'ptr" "ResetTimer" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Run : 
  WpMethodCall testing.pkg_name' "B'ptr" "Run" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_RunParallel : 
  WpMethodCall testing.pkg_name' "B'ptr" "RunParallel" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_SetBytes : 
  WpMethodCall testing.pkg_name' "B'ptr" "SetBytes" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_SetParallelism : 
  WpMethodCall testing.pkg_name' "B'ptr" "SetParallelism" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Setenv : 
  WpMethodCall testing.pkg_name' "B'ptr" "Setenv" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Skip : 
  WpMethodCall testing.pkg_name' "B'ptr" "Skip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_SkipNow : 
  WpMethodCall testing.pkg_name' "B'ptr" "SkipNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Skipf : 
  WpMethodCall testing.pkg_name' "B'ptr" "Skipf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_Skipped : 
  WpMethodCall testing.pkg_name' "B'ptr" "Skipped" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_StartTimer : 
  WpMethodCall testing.pkg_name' "B'ptr" "StartTimer" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_StopTimer : 
  WpMethodCall testing.pkg_name' "B'ptr" "StopTimer" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_TempDir : 
  WpMethodCall testing.pkg_name' "B'ptr" "TempDir" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_add : 
  WpMethodCall testing.pkg_name' "B'ptr" "add" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_checkFuzzFn : 
  WpMethodCall testing.pkg_name' "B'ptr" "checkFuzzFn" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_checkRaces : 
  WpMethodCall testing.pkg_name' "B'ptr" "checkRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_decorate : 
  WpMethodCall testing.pkg_name' "B'ptr" "decorate" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_doBench : 
  WpMethodCall testing.pkg_name' "B'ptr" "doBench" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_flushToParent : 
  WpMethodCall testing.pkg_name' "B'ptr" "flushToParent" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_frameSkip : 
  WpMethodCall testing.pkg_name' "B'ptr" "frameSkip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_launch : 
  WpMethodCall testing.pkg_name' "B'ptr" "launch" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_log : 
  WpMethodCall testing.pkg_name' "B'ptr" "log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_logDepth : 
  WpMethodCall testing.pkg_name' "B'ptr" "logDepth" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_private : 
  WpMethodCall testing.pkg_name' "B'ptr" "private" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_resetRaces : 
  WpMethodCall testing.pkg_name' "B'ptr" "resetRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_run : 
  WpMethodCall testing.pkg_name' "B'ptr" "run" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_run1 : 
  WpMethodCall testing.pkg_name' "B'ptr" "run1" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_runCleanup : 
  WpMethodCall testing.pkg_name' "B'ptr" "runCleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_runN : 
  WpMethodCall testing.pkg_name' "B'ptr" "runN" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_setRan : 
  WpMethodCall testing.pkg_name' "B'ptr" "setRan" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_B'ptr_trimOutput : 
  WpMethodCall testing.pkg_name' "B'ptr" "trimOutput" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_AllocedBytesPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "AllocedBytesPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_AllocsPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "AllocsPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_MemString : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "MemString" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_NsPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "NsPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_String : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult_mbPerSec : 
  WpMethodCall testing.pkg_name' "BenchmarkResult" "mbPerSec" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_AllocedBytesPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "AllocedBytesPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_AllocsPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "AllocsPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_MemString : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "MemString" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_NsPerOp : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "NsPerOp" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_String : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_BenchmarkResult'ptr_mbPerSec : 
  WpMethodCall testing.pkg_name' "BenchmarkResult'ptr" "mbPerSec" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_benchContext'ptr_processBench : 
  WpMethodCall testing.pkg_name' "benchContext'ptr" "processBench" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_PB'ptr_Next : 
  WpMethodCall testing.pkg_name' "PB'ptr" "Next" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_discard_Write : 
  WpMethodCall testing.pkg_name' "discard" "Write" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_discard'ptr_Write : 
  WpMethodCall testing.pkg_name' "discard'ptr" "Write" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_InternalExample'ptr_processRunResult : 
  WpMethodCall testing.pkg_name' "InternalExample'ptr" "processRunResult" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Add : 
  WpMethodCall testing.pkg_name' "F'ptr" "Add" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Cleanup : 
  WpMethodCall testing.pkg_name' "F'ptr" "Cleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Error : 
  WpMethodCall testing.pkg_name' "F'ptr" "Error" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Errorf : 
  WpMethodCall testing.pkg_name' "F'ptr" "Errorf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Fail : 
  WpMethodCall testing.pkg_name' "F'ptr" "Fail" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_FailNow : 
  WpMethodCall testing.pkg_name' "F'ptr" "FailNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Failed : 
  WpMethodCall testing.pkg_name' "F'ptr" "Failed" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Fatal : 
  WpMethodCall testing.pkg_name' "F'ptr" "Fatal" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Fatalf : 
  WpMethodCall testing.pkg_name' "F'ptr" "Fatalf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Fuzz : 
  WpMethodCall testing.pkg_name' "F'ptr" "Fuzz" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Helper : 
  WpMethodCall testing.pkg_name' "F'ptr" "Helper" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Log : 
  WpMethodCall testing.pkg_name' "F'ptr" "Log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Logf : 
  WpMethodCall testing.pkg_name' "F'ptr" "Logf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Name : 
  WpMethodCall testing.pkg_name' "F'ptr" "Name" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Setenv : 
  WpMethodCall testing.pkg_name' "F'ptr" "Setenv" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Skip : 
  WpMethodCall testing.pkg_name' "F'ptr" "Skip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_SkipNow : 
  WpMethodCall testing.pkg_name' "F'ptr" "SkipNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Skipf : 
  WpMethodCall testing.pkg_name' "F'ptr" "Skipf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_Skipped : 
  WpMethodCall testing.pkg_name' "F'ptr" "Skipped" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_TempDir : 
  WpMethodCall testing.pkg_name' "F'ptr" "TempDir" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_checkFuzzFn : 
  WpMethodCall testing.pkg_name' "F'ptr" "checkFuzzFn" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_checkRaces : 
  WpMethodCall testing.pkg_name' "F'ptr" "checkRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_decorate : 
  WpMethodCall testing.pkg_name' "F'ptr" "decorate" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_flushToParent : 
  WpMethodCall testing.pkg_name' "F'ptr" "flushToParent" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_frameSkip : 
  WpMethodCall testing.pkg_name' "F'ptr" "frameSkip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_log : 
  WpMethodCall testing.pkg_name' "F'ptr" "log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_logDepth : 
  WpMethodCall testing.pkg_name' "F'ptr" "logDepth" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_private : 
  WpMethodCall testing.pkg_name' "F'ptr" "private" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_report : 
  WpMethodCall testing.pkg_name' "F'ptr" "report" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_resetRaces : 
  WpMethodCall testing.pkg_name' "F'ptr" "resetRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_runCleanup : 
  WpMethodCall testing.pkg_name' "F'ptr" "runCleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_F'ptr_setRan : 
  WpMethodCall testing.pkg_name' "F'ptr" "setRan" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_fuzzResult_String : 
  WpMethodCall testing.pkg_name' "fuzzResult" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_fuzzResult'ptr_String : 
  WpMethodCall testing.pkg_name' "fuzzResult'ptr" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matcher'ptr_clearSubNames : 
  WpMethodCall testing.pkg_name' "matcher'ptr" "clearSubNames" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matcher'ptr_fullName : 
  WpMethodCall testing.pkg_name' "matcher'ptr" "fullName" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matcher'ptr_unique : 
  WpMethodCall testing.pkg_name' "matcher'ptr" "unique" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_simpleMatch_matches : 
  WpMethodCall testing.pkg_name' "simpleMatch" "matches" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_simpleMatch_verify : 
  WpMethodCall testing.pkg_name' "simpleMatch" "verify" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_simpleMatch'ptr_matches : 
  WpMethodCall testing.pkg_name' "simpleMatch'ptr" "matches" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_simpleMatch'ptr_verify : 
  WpMethodCall testing.pkg_name' "simpleMatch'ptr" "verify" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_alternationMatch_matches : 
  WpMethodCall testing.pkg_name' "alternationMatch" "matches" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_alternationMatch_verify : 
  WpMethodCall testing.pkg_name' "alternationMatch" "verify" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_alternationMatch'ptr_matches : 
  WpMethodCall testing.pkg_name' "alternationMatch'ptr" "matches" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_alternationMatch'ptr_verify : 
  WpMethodCall testing.pkg_name' "alternationMatch'ptr" "verify" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyFlag'ptr_Get : 
  WpMethodCall testing.pkg_name' "chattyFlag'ptr" "Get" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyFlag'ptr_IsBoolFlag : 
  WpMethodCall testing.pkg_name' "chattyFlag'ptr" "IsBoolFlag" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyFlag'ptr_Set : 
  WpMethodCall testing.pkg_name' "chattyFlag'ptr" "Set" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyFlag'ptr_String : 
  WpMethodCall testing.pkg_name' "chattyFlag'ptr" "String" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyFlag'ptr_prefix : 
  WpMethodCall testing.pkg_name' "chattyFlag'ptr" "prefix" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyPrinter'ptr_Printf : 
  WpMethodCall testing.pkg_name' "chattyPrinter'ptr" "Printf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyPrinter'ptr_Updatef : 
  WpMethodCall testing.pkg_name' "chattyPrinter'ptr" "Updatef" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_chattyPrinter'ptr_prefix : 
  WpMethodCall testing.pkg_name' "chattyPrinter'ptr" "prefix" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Cleanup : 
  WpMethodCall testing.pkg_name' "common'ptr" "Cleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Error : 
  WpMethodCall testing.pkg_name' "common'ptr" "Error" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Errorf : 
  WpMethodCall testing.pkg_name' "common'ptr" "Errorf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Fail : 
  WpMethodCall testing.pkg_name' "common'ptr" "Fail" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_FailNow : 
  WpMethodCall testing.pkg_name' "common'ptr" "FailNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Failed : 
  WpMethodCall testing.pkg_name' "common'ptr" "Failed" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Fatal : 
  WpMethodCall testing.pkg_name' "common'ptr" "Fatal" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Fatalf : 
  WpMethodCall testing.pkg_name' "common'ptr" "Fatalf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Helper : 
  WpMethodCall testing.pkg_name' "common'ptr" "Helper" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Log : 
  WpMethodCall testing.pkg_name' "common'ptr" "Log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Logf : 
  WpMethodCall testing.pkg_name' "common'ptr" "Logf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Name : 
  WpMethodCall testing.pkg_name' "common'ptr" "Name" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Setenv : 
  WpMethodCall testing.pkg_name' "common'ptr" "Setenv" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Skip : 
  WpMethodCall testing.pkg_name' "common'ptr" "Skip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_SkipNow : 
  WpMethodCall testing.pkg_name' "common'ptr" "SkipNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Skipf : 
  WpMethodCall testing.pkg_name' "common'ptr" "Skipf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_Skipped : 
  WpMethodCall testing.pkg_name' "common'ptr" "Skipped" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_TempDir : 
  WpMethodCall testing.pkg_name' "common'ptr" "TempDir" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_checkFuzzFn : 
  WpMethodCall testing.pkg_name' "common'ptr" "checkFuzzFn" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_checkRaces : 
  WpMethodCall testing.pkg_name' "common'ptr" "checkRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_decorate : 
  WpMethodCall testing.pkg_name' "common'ptr" "decorate" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_flushToParent : 
  WpMethodCall testing.pkg_name' "common'ptr" "flushToParent" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_frameSkip : 
  WpMethodCall testing.pkg_name' "common'ptr" "frameSkip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_log : 
  WpMethodCall testing.pkg_name' "common'ptr" "log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_logDepth : 
  WpMethodCall testing.pkg_name' "common'ptr" "logDepth" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_private : 
  WpMethodCall testing.pkg_name' "common'ptr" "private" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_resetRaces : 
  WpMethodCall testing.pkg_name' "common'ptr" "resetRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_runCleanup : 
  WpMethodCall testing.pkg_name' "common'ptr" "runCleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_common'ptr_setRan : 
  WpMethodCall testing.pkg_name' "common'ptr" "setRan" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_indenter_Write : 
  WpMethodCall testing.pkg_name' "indenter" "Write" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_indenter'ptr_Write : 
  WpMethodCall testing.pkg_name' "indenter'ptr" "Write" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Cleanup : 
  WpMethodCall testing.pkg_name' "T'ptr" "Cleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Deadline : 
  WpMethodCall testing.pkg_name' "T'ptr" "Deadline" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Error : 
  WpMethodCall testing.pkg_name' "T'ptr" "Error" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Errorf : 
  WpMethodCall testing.pkg_name' "T'ptr" "Errorf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Fail : 
  WpMethodCall testing.pkg_name' "T'ptr" "Fail" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_FailNow : 
  WpMethodCall testing.pkg_name' "T'ptr" "FailNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Failed : 
  WpMethodCall testing.pkg_name' "T'ptr" "Failed" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Fatal : 
  WpMethodCall testing.pkg_name' "T'ptr" "Fatal" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Fatalf : 
  WpMethodCall testing.pkg_name' "T'ptr" "Fatalf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Helper : 
  WpMethodCall testing.pkg_name' "T'ptr" "Helper" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Log : 
  WpMethodCall testing.pkg_name' "T'ptr" "Log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Logf : 
  WpMethodCall testing.pkg_name' "T'ptr" "Logf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Name : 
  WpMethodCall testing.pkg_name' "T'ptr" "Name" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Parallel : 
  WpMethodCall testing.pkg_name' "T'ptr" "Parallel" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Run : 
  WpMethodCall testing.pkg_name' "T'ptr" "Run" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Setenv : 
  WpMethodCall testing.pkg_name' "T'ptr" "Setenv" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Skip : 
  WpMethodCall testing.pkg_name' "T'ptr" "Skip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_SkipNow : 
  WpMethodCall testing.pkg_name' "T'ptr" "SkipNow" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Skipf : 
  WpMethodCall testing.pkg_name' "T'ptr" "Skipf" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_Skipped : 
  WpMethodCall testing.pkg_name' "T'ptr" "Skipped" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_TempDir : 
  WpMethodCall testing.pkg_name' "T'ptr" "TempDir" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_checkFuzzFn : 
  WpMethodCall testing.pkg_name' "T'ptr" "checkFuzzFn" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_checkRaces : 
  WpMethodCall testing.pkg_name' "T'ptr" "checkRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_decorate : 
  WpMethodCall testing.pkg_name' "T'ptr" "decorate" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_flushToParent : 
  WpMethodCall testing.pkg_name' "T'ptr" "flushToParent" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_frameSkip : 
  WpMethodCall testing.pkg_name' "T'ptr" "frameSkip" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_log : 
  WpMethodCall testing.pkg_name' "T'ptr" "log" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_logDepth : 
  WpMethodCall testing.pkg_name' "T'ptr" "logDepth" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_private : 
  WpMethodCall testing.pkg_name' "T'ptr" "private" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_report : 
  WpMethodCall testing.pkg_name' "T'ptr" "report" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_resetRaces : 
  WpMethodCall testing.pkg_name' "T'ptr" "resetRaces" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_runCleanup : 
  WpMethodCall testing.pkg_name' "T'ptr" "runCleanup" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_T'ptr_setRan : 
  WpMethodCall testing.pkg_name' "T'ptr" "setRan" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_testContext'ptr_release : 
  WpMethodCall testing.pkg_name' "testContext'ptr" "release" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_testContext'ptr_waitParallel : 
  WpMethodCall testing.pkg_name' "testContext'ptr" "waitParallel" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_CheckCorpus : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "CheckCorpus" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_CoordinateFuzzing : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "CoordinateFuzzing" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_ImportPath : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "ImportPath" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_InitRuntimeCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "InitRuntimeCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_MatchString : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "MatchString" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_ReadCorpus : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "ReadCorpus" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_ResetCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "ResetCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_RunFuzzWorker : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "RunFuzzWorker" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_SetPanicOnExit0 : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "SetPanicOnExit0" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_SnapshotCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "SnapshotCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_StartCPUProfile : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "StartCPUProfile" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_StartTestLog : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "StartTestLog" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_StopCPUProfile : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "StopCPUProfile" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_StopTestLog : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "StopTestLog" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly_WriteProfileTo : 
  WpMethodCall testing.pkg_name' "matchStringOnly" "WriteProfileTo" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_CheckCorpus : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "CheckCorpus" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_CoordinateFuzzing : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "CoordinateFuzzing" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_ImportPath : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "ImportPath" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_InitRuntimeCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "InitRuntimeCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_MatchString : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "MatchString" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_ReadCorpus : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "ReadCorpus" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_ResetCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "ResetCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_RunFuzzWorker : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "RunFuzzWorker" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_SetPanicOnExit0 : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "SetPanicOnExit0" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_SnapshotCoverage : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "SnapshotCoverage" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_StartCPUProfile : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "StartCPUProfile" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_StartTestLog : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "StartTestLog" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_StopCPUProfile : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "StopCPUProfile" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_StopTestLog : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "StopTestLog" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_matchStringOnly'ptr_WriteProfileTo : 
  WpMethodCall testing.pkg_name' "matchStringOnly'ptr" "WriteProfileTo" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_Run : 
  WpMethodCall testing.pkg_name' "M'ptr" "Run" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_after : 
  WpMethodCall testing.pkg_name' "M'ptr" "after" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_before : 
  WpMethodCall testing.pkg_name' "M'ptr" "before" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_startAlarm : 
  WpMethodCall testing.pkg_name' "M'ptr" "startAlarm" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_stopAlarm : 
  WpMethodCall testing.pkg_name' "M'ptr" "stopAlarm" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

Global Instance wp_method_call_M'ptr_writeProfiles : 
  WpMethodCall testing.pkg_name' "M'ptr" "writeProfiles" _ is_defined :=
  ltac:(apply wp_method_call'; reflexivity).

End defs.
End testing.
