(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.generatedproof.github_com.mit_pdos.gokv.tutorial.objectstore.dir.chunkhandle_gk.
Require Export New.golang.theory.

Require Export New.code.github_com.mit_pdos.gokv.tutorial.objectstore.dir.preparedread_gk.

Set Default Proof Using "Type".

Module preparedread_gk.

(* type preparedread_gk.S *)
Module S.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Handles' : slice.t;
}.
End def.
End S.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent preparedread_gk.S.
#[local] Typeclasses Transparent preparedread_gk.S.

Global Instance S_wf : struct.Wf preparedread_gk.S.
Proof. apply _. Qed.

Global Instance settable_S : Settable S.t :=
  settable! S.mk < S.Handles' >.
Global Instance into_val_S : IntoVal S.t :=
  {| to_val_def v :=
    struct.val_aux preparedread_gk.S [
    "Handles" ::= #(S.Handles' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_S : IntoValTyped S.t preparedread_gk.S :=
{|
  default_val := S.mk (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_S_Handles : IntoValStructField "Handles" preparedread_gk.S S.Handles'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_S Handles':
  PureWp True
    (struct.make #preparedread_gk.S (alist_val [
      "Handles" ::= #Handles'
    ]))%struct
    #(S.mk Handles').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance S_struct_fields_split dq l (v : S.t) :
  StructFieldsSplit dq l v (
    "HHandles" ∷ l ↦s[preparedread_gk.S :: "Handles"]{dq} v.(S.Handles')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.

  solve_field_ref_f.
Qed.

End instances.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_preparedread_gk : IsPkgDefinedPure preparedread_gk :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single preparedread_gk ∧
      is_pkg_defined_pure code.github_com.tchajed.marshal.marshal ∧
      is_pkg_defined_pure code.github_com.mit_pdos.gokv.tutorial.objectstore.dir.chunkhandle_gk.chunkhandle_gk;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_preparedread_gk : IsPkgDefined preparedread_gk :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single preparedread_gk ∗
       is_pkg_defined code.github_com.tchajed.marshal.marshal ∗
       is_pkg_defined code.github_com.mit_pdos.gokv.tutorial.objectstore.dir.chunkhandle_gk.chunkhandle_gk)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_Marshal :
  WpFuncCall preparedread_gk.Marshal _ (is_pkg_defined preparedread_gk) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_Unmarshal :
  WpFuncCall preparedread_gk.Unmarshal _ (is_pkg_defined preparedread_gk) :=
  ltac:(solve_wp_func_call).

End names.
End preparedread_gk.
