-- autogenerated by goose proofgen; do not modify
import Perennial.Proof.ProofPrelude
import Perennial.GeneratedProof.bytes
import Perennial.GeneratedProof.context
import Perennial.GeneratedProof.crypto.rand
import Perennial.GeneratedProof.encoding.binary
import Perennial.GeneratedProof.errors
import Perennial.GeneratedProof.fmt
import Perennial.GeneratedProof.go_etcd_io.raft.v3.confchange
import Perennial.GeneratedProof.go_etcd_io.raft.v3.quorum
import Perennial.GeneratedProof.go_etcd_io.raft.v3.raftpb
import Perennial.GeneratedProof.go_etcd_io.raft.v3.tracker
import Perennial.GeneratedProof.io
import Perennial.GeneratedProof.log
import Perennial.GeneratedProof.math
import Perennial.GeneratedProof.math.big
import Perennial.GeneratedProof.os
import Perennial.GeneratedProof.slices
import Perennial.GeneratedProof.strings
import Perennial.GeneratedProof.sync
import Perennial.Golang.Theory
import Perennial.Code.go_etcd_io.raft.v3
import Perennial.GeneratedProof.go_etcd_io.raft.v3.chunk1
import Perennial.GeneratedProof.go_etcd_io.raft.v3.chunk2

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
open Iris Iris.BI
noncomputable section
namespace go_etcd_io.raft.v3

namespace raftLog
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : go_etcd_io.raft.v3.Assumptions]

instance raftLog_typed_pointsto :
    TypedPointsto (GF := GF) go_etcd_io.raft.v3.raftLog.t where
  typed_pointsto_def l v dq := iprop(
    "storage" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"storage" l) v.storage' dq ∗
    "unstable" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"unstable" l) v.unstable' dq ∗
    "committed" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"committed" l) v.committed' dq ∗
    "applying" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applying" l) v.applying' dq ∗
    "applied" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applied" l) v.applied' dq ∗
    "logger" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"logger" l) v.logger' dq ∗
    "maxApplyingEntsSize" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"maxApplyingEntsSize" l) v.maxApplyingEntsSize' dq ∗
    "applyingEntsSize" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsSize" l) v.applyingEntsSize' dq ∗
    "applyingEntsPaused" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsPaused" l) v.applyingEntsPaused' dq ∗
    "_" ∷ True)
  typed_pointsto_def_dfractional := by solve_typed_pointsto_dfractional
  typed_pointsto_def_timeless := by solve_typed_pointsto_timeless
  typed_pointsto_agree := by solve_typed_pointsto_agree

instance raftLog_into_val_typed :
    IntoValTypedUnderlying (GF := GF) go_etcd_io.raft.v3.raftLog.t go_etcd_io.raft.v3.«raftLogⁱᵐᵖˡ» := by
  solve_into_val_typed_struct

instance raftLog_access_load_storage (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"storage" l) v.storage' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"storage" l) v.storage' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_storage (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (storage' : go_etcd_io.raft.v3.Storage.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"storage" l) v.storage' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"storage" l) storage' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with storage' := storage' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_unstable (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"unstable" l) v.unstable' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"unstable" l) v.unstable' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_unstable (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (unstable' : go_etcd_io.raft.v3.unstable.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"unstable" l) v.unstable' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"unstable" l) unstable' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with unstable' := unstable' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_committed (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"committed" l) v.committed' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"committed" l) v.committed' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_committed (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (committed' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"committed" l) v.committed' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"committed" l) committed' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with committed' := committed' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_applying (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applying" l) v.applying' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applying" l) v.applying' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_applying (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (applying' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applying" l) v.applying' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applying" l) applying' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with applying' := applying' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_applied (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applied" l) v.applied' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applied" l) v.applied' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_applied (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (applied' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applied" l) v.applied' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applied" l) applied' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with applied' := applied' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_logger (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"logger" l) v.logger' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"logger" l) v.logger' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_logger (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (logger' : go_etcd_io.raft.v3.Logger.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"logger" l) v.logger' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"logger" l) logger' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with logger' := logger' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_maxApplyingEntsSize (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"maxApplyingEntsSize" l) v.maxApplyingEntsSize' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"maxApplyingEntsSize" l) v.maxApplyingEntsSize' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_maxApplyingEntsSize (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (maxApplyingEntsSize' : go_etcd_io.raft.v3.entryEncodingSize.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"maxApplyingEntsSize" l) v.maxApplyingEntsSize' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"maxApplyingEntsSize" l) maxApplyingEntsSize' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with maxApplyingEntsSize' := maxApplyingEntsSize' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_applyingEntsSize (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsSize" l) v.applyingEntsSize' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsSize" l) v.applyingEntsSize' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_applyingEntsSize (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (applyingEntsSize' : go_etcd_io.raft.v3.entryEncodingSize.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsSize" l) v.applyingEntsSize' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsSize" l) applyingEntsSize' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with applyingEntsSize' := applyingEntsSize' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_load_applyingEntsPaused (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsPaused" l) v.applyingEntsPaused' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsPaused" l) v.applyingEntsPaused' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance raftLog_access_store_applyingEntsPaused (l : loc) (v : go_etcd_io.raft.v3.raftLog.t) (applyingEntsPaused' : Bool) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsPaused" l) v.applyingEntsPaused' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.raftLog.t go!"applyingEntsPaused" l) applyingEntsPaused' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with applyingEntsPaused' := applyingEntsPaused' } : go_etcd_io.raft.v3.raftLog.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end raftLog

namespace BasicStatus
section def_

variable [ext : ffi_syntax] [ffi : ffi_model] [ffi_interp ffi] [ffi_semantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : heapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : go_etcd_io.raft.v3.Assumptions]

instance BasicStatus_typed_pointsto :
    TypedPointsto (GF := GF) go_etcd_io.raft.v3.BasicStatus.t where
  typed_pointsto_def l v dq := iprop(
    "ID" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"ID" l) v.ID' dq ∗
    "HardState" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"HardState" l) v.HardState' dq ∗
    "SoftState" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"SoftState" l) v.SoftState' dq ∗
    "Applied" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"Applied" l) v.Applied' dq ∗
    "LeadTransferee" ∷ typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"LeadTransferee" l) v.LeadTransferee' dq ∗
    "_" ∷ True)
  typed_pointsto_def_dfractional := by solve_typed_pointsto_dfractional
  typed_pointsto_def_timeless := by solve_typed_pointsto_timeless
  typed_pointsto_agree := by solve_typed_pointsto_agree

instance BasicStatus_into_val_typed :
    IntoValTypedUnderlying (GF := GF) go_etcd_io.raft.v3.BasicStatus.t go_etcd_io.raft.v3.«BasicStatusⁱᵐᵖˡ» := by
  solve_into_val_typed_struct

instance BasicStatus_access_load_ID (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"ID" l) v.ID' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"ID" l) v.ID' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_store_ID (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (ID' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"ID" l) v.ID' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"ID" l) ID' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with ID' := ID' } : go_etcd_io.raft.v3.BasicStatus.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_load_HardState (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"HardState" l) v.HardState' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"HardState" l) v.HardState' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_store_HardState (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (HardState' : go_etcd_io.raft.v3.raftpb.HardState.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"HardState" l) v.HardState' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"HardState" l) HardState' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with HardState' := HardState' } : go_etcd_io.raft.v3.BasicStatus.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_load_SoftState (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"SoftState" l) v.SoftState' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"SoftState" l) v.SoftState' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_store_SoftState (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (SoftState' : go_etcd_io.raft.v3.SoftState.t) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"SoftState" l) v.SoftState' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"SoftState" l) SoftState' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with SoftState' := SoftState' } : go_etcd_io.raft.v3.BasicStatus.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_load_Applied (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"Applied" l) v.Applied' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"Applied" l) v.Applied' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_store_Applied (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (Applied' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"Applied" l) v.Applied' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"Applied" l) Applied' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with Applied' := Applied' } : go_etcd_io.raft.v3.BasicStatus.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_load_LeadTransferee (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"LeadTransferee" l) v.LeadTransferee' dq)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"LeadTransferee" l) v.LeadTransferee' dq)
      (typed_pointsto l v dq) (typed_pointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance BasicStatus_access_store_LeadTransferee (l : loc) (v : go_etcd_io.raft.v3.BasicStatus.t) (LeadTransferee' : w64) :
    AccessStrict (PROP := IProp GF)
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"LeadTransferee" l) v.LeadTransferee' (DFrac.own 1))
      (typed_pointsto (struct_field_ref go_etcd_io.raft.v3.BasicStatus.t go!"LeadTransferee" l) LeadTransferee' (DFrac.own 1))
      (typed_pointsto l v (DFrac.own 1)) (typed_pointsto l ({ v with LeadTransferee' := LeadTransferee' } : go_etcd_io.raft.v3.BasicStatus.t) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end BasicStatus

end go_etcd_io.raft.v3
end
end Perennial
