-- autogenerated by goose proofgen; do not modify
import Perennial.Proof.ProofPrelude
import Perennial.GeneratedProof.bytes
import Perennial.GeneratedProof.context
import Perennial.GeneratedProof.crypto.rand
import Perennial.GeneratedProof.encoding.binary
import Perennial.GeneratedProof.errors
import Perennial.GeneratedProof.fmt
import Perennial.GeneratedProof.go_etcd_io.raft.v3.confchange
import Perennial.GeneratedProof.go_etcd_io.raft.v3.quorum
import Perennial.GeneratedProof.go_etcd_io.raft.v3.raftpb
import Perennial.GeneratedProof.go_etcd_io.raft.v3.tracker
import Perennial.GeneratedProof.io
import Perennial.GeneratedProof.log
import Perennial.GeneratedProof.math
import Perennial.GeneratedProof.math.big
import Perennial.GeneratedProof.os
import Perennial.GeneratedProof.slices
import Perennial.GeneratedProof.strings
import Perennial.GeneratedProof.sync
import Perennial.Golang.Theory
import Perennial.Code.go_etcd_io.raft.v3
import Perennial.GeneratedProof.go_etcd_io.raft.v3.chunk3

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.iris.style.nameCheck false
set_option linter.iris.dupNamespace false

namespace Perennial
open Iris Iris.BI
noncomputable section
namespace go_etcd_io.raft.v3

namespace Status
section def_

variable [ext : FfiSyntax] [ffi : FfiModel] [FfiInterp ffi] [FfiSemantics ext ffi] [go_gctx : GoGlobalContext]
variable {hlc : HasLC} {GF : BundledGFunctors} [hG : HeapGS hlc GF]
variable [sem : go.Semantics]
variable [package_sem' : go_etcd_io.raft.v3.Assumptions]

instance Status_typed_pointsto :
    TypedPointsto (GF := GF) go_etcd_io.raft.v3.Status where
  typedPointstoDef l v dq := iprop(
    "BasicStatus" ∷ typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"BasicStatus" l) v.BasicStatus' dq ∗
    "Config" ∷ typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Config" l) v.Config' dq ∗
    "Progress" ∷ typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Progress" l) v.Progress' dq ∗
    "_" ∷ True)
  typedPointstoDef_dfractional := by solve_typed_pointsto_dfractional
  typedPointstoDef_timeless := by solve_typed_pointsto_timeless
  typedPointsto_agree := by solve_typed_pointsto_agree

instance Status_into_val_typed :
    IntoValTypedUnderlying (GF := GF) go_etcd_io.raft.v3.Status go_etcd_io.raft.v3.Status.underlying := by
  solve_into_val_typed_struct

instance Status_access_load_BasicStatus (l : Loc) (v : go_etcd_io.raft.v3.Status) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"BasicStatus" l) v.BasicStatus' dq)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"BasicStatus" l) v.BasicStatus' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Status_access_store_BasicStatus (l : Loc) (v : go_etcd_io.raft.v3.Status) (BasicStatus' : go_etcd_io.raft.v3.BasicStatus) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"BasicStatus" l) v.BasicStatus' (DFrac.own 1))
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"BasicStatus" l) BasicStatus' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with BasicStatus' := BasicStatus' } : go_etcd_io.raft.v3.Status) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance Status_access_load_Config (l : Loc) (v : go_etcd_io.raft.v3.Status) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Config" l) v.Config' dq)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Config" l) v.Config' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Status_access_store_Config (l : Loc) (v : go_etcd_io.raft.v3.Status) (Config' : go_etcd_io.raft.v3.tracker.Config) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Config" l) v.Config' (DFrac.own 1))
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Config" l) Config' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with Config' := Config' } : go_etcd_io.raft.v3.Status) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

instance Status_access_load_Progress (l : Loc) (v : go_etcd_io.raft.v3.Status) (dq : DFrac) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Progress" l) v.Progress' dq)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Progress" l) v.Progress' dq)
      (typedPointsto l v dq) (typedPointsto l v dq) :=
 by
  solve_pointsto_access_struct

instance Status_access_store_Progress (l : Loc) (v : go_etcd_io.raft.v3.Status) (Progress' : map.t) :
    AccessStrict (PROP := IProp GF)
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Progress" l) v.Progress' (DFrac.own 1))
      (typedPointsto (structFieldRef go_etcd_io.raft.v3.Status go!"Progress" l) Progress' (DFrac.own 1))
      (typedPointsto l v (DFrac.own 1)) (typedPointsto l ({ v with Progress' := Progress' } : go_etcd_io.raft.v3.Status) (DFrac.own 1)) :=
 by
  solve_pointsto_access_struct

end def_
end Status

end go_etcd_io.raft.v3
end
end Perennial
