name: CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # every day at 9am UTC (4am EST)
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        coq_version:
          - dev
          - "8.16"
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: "4.13-flambda"
          install: |
            startGroup Install dependencies
              sudo apt-get update
              sudo apt-get install -y python3 python3-pip python3-pandas sqlite3
              pip3 install -r etc/requirements.txt
            endGroup
          before_script: |
            sudo chown -R coq:coq . # workaround a permission issue
          script: |
            startGroup Build
              make -j2 -k ci
            endGroup
          after_script: |
            startGroup Create timing report
              ./etc/timing-report.py --max-files 50
            endGroup
          uninstall: |
            make clean
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

  build-vos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - dev
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: "4.13-flambda"
          install: |
            startGroup Install dependencies
              sudo apt-get update
              sudo apt-get install -y python3 python3-pip python3-pandas sqlite3
              pip3 install -r etc/requirements.txt
            endGroup
          before_script: |
            sudo chown -R coq:coq . # workaround a permission issue
          script: |
            startGroup Build
              make -j2 -k vos
            endGroup
          after_script: |
            startGroup Create timing report
              ./etc/timing-report.py --vos --max-files 50
            endGroup
          uninstall: |
            make clean
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

  check-goose:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: check that Goosed files are clean
        run: etc/ci-goose-check.sh
