# mostly stolen from
# https://github.com/mit-plv/bedrock2/blob/720023ddce9ba114f451cf3f0ebc8f9ee3002893/.github/workflows/main.yml

name: Update coq/tested

on:
  schedule:
    # run at 06:59 UTC (3am eastern) each day
    - cron: "59 6 * * *"
  # allow running action manually.
  workflow_dispatch:

jobs:
  update_branch:
    runs-on: ubuntu-latest
    name: Update coq/tested
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
        # this branch is protected so the push will fail if CI hasn't succeeded on
        # this commit
      - name: Push to coq/tested
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "coq/tested"
