(* autogenerated from io *)
Require Export New.code.errors.
Require Export New.code.sync.

From New.golang Require Import defn.
Definition io : go_string := "io".

Module io.

Section code.
Context `{ffi_syntax}.


Axiom SeekStart : Z.

Axiom SeekCurrent : Z.

Axiom SeekEnd : Z.

Definition ErrShortWrite : go_string := "io.ErrShortWrite"%go.

Axiom ErrShortWrite'init : val.

Definition errInvalidWrite : go_string := "io.errInvalidWrite"%go.

Axiom errInvalidWrite'init : val.

Definition ErrShortBuffer : go_string := "io.ErrShortBuffer"%go.

Axiom ErrShortBuffer'init : val.

Definition EOF : go_string := "io.EOF"%go.

Axiom EOF'init : val.

Definition ErrUnexpectedEOF : go_string := "io.ErrUnexpectedEOF"%go.

Axiom ErrUnexpectedEOF'init : val.

Definition ErrNoProgress : go_string := "io.ErrNoProgress"%go.

Axiom ErrNoProgress'init : val.

Definition Readerⁱᵐᵖˡ : go.type := go.InterfaceType [go.MethodElem #"Read"%go (go.Signature [go.SliceType go.byte] #false [go.int; go.error])].

Definition Writerⁱᵐᵖˡ : go.type := go.InterfaceType [go.MethodElem #"Write"%go (go.Signature [go.SliceType go.byte] #false [go.int; go.error])].

Axiom Closerⁱᵐᵖˡ : go.type.

Axiom Seekerⁱᵐᵖˡ : go.type.

Axiom ReadWriterⁱᵐᵖˡ : go.type.

Axiom ReadCloserⁱᵐᵖˡ : go.type.

Axiom WriteCloserⁱᵐᵖˡ : go.type.

Axiom ReadWriteCloserⁱᵐᵖˡ : go.type.

Axiom ReadSeekerⁱᵐᵖˡ : go.type.

Axiom ReadSeekCloserⁱᵐᵖˡ : go.type.

Axiom WriteSeekerⁱᵐᵖˡ : go.type.

Axiom ReadWriteSeekerⁱᵐᵖˡ : go.type.

Axiom ReaderFromⁱᵐᵖˡ : go.type.

Axiom WriterToⁱᵐᵖˡ : go.type.

Axiom ReaderAtⁱᵐᵖˡ : go.type.

Axiom WriterAtⁱᵐᵖˡ : go.type.

Axiom ByteReaderⁱᵐᵖˡ : go.type.

Axiom ByteScannerⁱᵐᵖˡ : go.type.

Axiom ByteWriterⁱᵐᵖˡ : go.type.

Axiom RuneReaderⁱᵐᵖˡ : go.type.

Axiom RuneScannerⁱᵐᵖˡ : go.type.

Axiom StringWriterⁱᵐᵖˡ : go.type.

Definition WriteString : go_string := "io.WriteString"%go.

Definition ReadAtLeast : go_string := "io.ReadAtLeast"%go.

Definition ReadFull : go_string := "io.ReadFull"%go.

Definition CopyN : go_string := "io.CopyN"%go.

Definition Copy : go_string := "io.Copy"%go.

Definition CopyBuffer : go_string := "io.CopyBuffer"%go.

Definition copyBuffer : go_string := "io.copyBuffer"%go.

Definition LimitReader : go_string := "io.LimitReader"%go.

Axiom LimitedReaderⁱᵐᵖˡ : go.type.

Definition NewSectionReader : go_string := "io.NewSectionReader"%go.

Axiom SectionReaderⁱᵐᵖˡ : go.type.

Definition errWhence : go_string := "io.errWhence"%go.

Axiom errWhence'init : val.

Definition errOffset : go_string := "io.errOffset"%go.

Axiom errOffset'init : val.

Axiom OffsetWriterⁱᵐᵖˡ : go.type.

Definition NewOffsetWriter : go_string := "io.NewOffsetWriter"%go.

Definition TeeReader : go_string := "io.TeeReader"%go.

Axiom teeReaderⁱᵐᵖˡ : go.type.

Definition Discard : go_string := "io.Discard"%go.

Axiom Discard'init : val.

Axiom discardⁱᵐᵖˡ : go.type.

Definition blackHolePool : go_string := "io.blackHolePool"%go.

Axiom blackHolePool'init : val.

Definition NopCloser : go_string := "io.NopCloser"%go.

Axiom nopCloserⁱᵐᵖˡ : go.type.

Axiom nopCloserWriterToⁱᵐᵖˡ : go.type.

Definition ReadAll : go_string := "io.ReadAll"%go.

Axiom eofReaderⁱᵐᵖˡ : go.type.

Axiom multiReaderⁱᵐᵖˡ : go.type.

Definition MultiReader : go_string := "io.MultiReader"%go.

Axiom multiWriterⁱᵐᵖˡ : go.type.

Definition MultiWriter : go_string := "io.MultiWriter"%go.

Axiom onceErrorⁱᵐᵖˡ : go.type.

Definition ErrClosedPipe : go_string := "io.ErrClosedPipe"%go.

Axiom ErrClosedPipe'init : val.

Axiom pipeⁱᵐᵖˡ : go.type.

Axiom PipeReaderⁱᵐᵖˡ : go.type.

Axiom PipeWriterⁱᵐᵖˡ : go.type.

Definition Pipe : go_string := "io.Pipe"%go.

Definition Reader : go.type := go.Named "io.Reader"%go [].

Definition Writer : go.type := go.Named "io.Writer"%go [].

Definition Closer : go.type := go.Named "io.Closer"%go [].

Definition Seeker : go.type := go.Named "io.Seeker"%go [].

Definition ReadWriter : go.type := go.Named "io.ReadWriter"%go [].

Definition ReadCloser : go.type := go.Named "io.ReadCloser"%go [].

Definition WriteCloser : go.type := go.Named "io.WriteCloser"%go [].

Definition ReadWriteCloser : go.type := go.Named "io.ReadWriteCloser"%go [].

Definition ReadSeeker : go.type := go.Named "io.ReadSeeker"%go [].

Definition ReadSeekCloser : go.type := go.Named "io.ReadSeekCloser"%go [].

Definition WriteSeeker : go.type := go.Named "io.WriteSeeker"%go [].

Definition ReadWriteSeeker : go.type := go.Named "io.ReadWriteSeeker"%go [].

Definition ReaderFrom : go.type := go.Named "io.ReaderFrom"%go [].

Definition WriterTo : go.type := go.Named "io.WriterTo"%go [].

Definition ReaderAt : go.type := go.Named "io.ReaderAt"%go [].

Definition WriterAt : go.type := go.Named "io.WriterAt"%go [].

Definition ByteReader : go.type := go.Named "io.ByteReader"%go [].

Definition ByteScanner : go.type := go.Named "io.ByteScanner"%go [].

Definition ByteWriter : go.type := go.Named "io.ByteWriter"%go [].

Definition RuneReader : go.type := go.Named "io.RuneReader"%go [].

Definition RuneScanner : go.type := go.Named "io.RuneScanner"%go [].

Definition StringWriter : go.type := go.Named "io.StringWriter"%go [].

Definition LimitedReader : go.type := go.Named "io.LimitedReader"%go [].

Definition SectionReader : go.type := go.Named "io.SectionReader"%go [].

Definition OffsetWriter : go.type := go.Named "io.OffsetWriter"%go [].

Definition teeReader : go.type := go.Named "io.teeReader"%go [].

Definition discard : go.type := go.Named "io.discard"%go [].

Definition nopCloser : go.type := go.Named "io.nopCloser"%go [].

Definition nopCloserWriterTo : go.type := go.Named "io.nopCloserWriterTo"%go [].

Definition eofReader : go.type := go.Named "io.eofReader"%go [].

Definition multiReader : go.type := go.Named "io.multiReader"%go [].

Definition multiWriter : go.type := go.Named "io.multiWriter"%go [].

Definition onceError : go.type := go.Named "io.onceError"%go [].

Definition pipe : go.type := go.Named "io.pipe"%go [].

Definition PipeReader : go.type := go.Named "io.PipeReader"%go [].

Definition PipeWriter : go.type := go.Named "io.PipeWriter"%go [].

Axiom WriteStringⁱᵐᵖˡ : val.

Axiom ReadAtLeastⁱᵐᵖˡ : val.

Axiom ReadFullⁱᵐᵖˡ : val.

Axiom CopyNⁱᵐᵖˡ : val.

Axiom Copyⁱᵐᵖˡ : val.

Axiom CopyBufferⁱᵐᵖˡ : val.

Axiom copyBufferⁱᵐᵖˡ : val.

Axiom LimitReaderⁱᵐᵖˡ : val.

Axiom NewSectionReaderⁱᵐᵖˡ : val.

Axiom NewOffsetWriterⁱᵐᵖˡ : val.

Axiom TeeReaderⁱᵐᵖˡ : val.

Axiom NopCloserⁱᵐᵖˡ : val.

Axiom ReadAllⁱᵐᵖˡ : val.

Axiom MultiReaderⁱᵐᵖˡ : val.

Axiom MultiWriterⁱᵐᵖˡ : val.

Axiom Pipeⁱᵐᵖˡ : val.

Definition functions' : list (go_string * val) := [(WriteString, WriteStringⁱᵐᵖˡ); (ReadAtLeast, ReadAtLeastⁱᵐᵖˡ); (ReadFull, ReadFullⁱᵐᵖˡ); (CopyN, CopyNⁱᵐᵖˡ); (Copy, Copyⁱᵐᵖˡ); (CopyBuffer, CopyBufferⁱᵐᵖˡ); (copyBuffer, copyBufferⁱᵐᵖˡ); (LimitReader, LimitReaderⁱᵐᵖˡ); (NewSectionReader, NewSectionReaderⁱᵐᵖˡ); (NewOffsetWriter, NewOffsetWriterⁱᵐᵖˡ); (TeeReader, TeeReaderⁱᵐᵖˡ); (NopCloser, NopCloserⁱᵐᵖˡ); (ReadAll, ReadAllⁱᵐᵖˡ); (MultiReader, MultiReaderⁱᵐᵖˡ); (MultiWriter, MultiWriterⁱᵐᵖˡ); (Pipe, Pipeⁱᵐᵖˡ)].

#[global] Instance info' : PkgInfo io.io :=
  {|
    pkg_imported_pkgs := [code.errors.errors; code.sync.sync];
  |}.

Axiom _'init : val.

Definition initialize' : val :=
  λ: <>,
    package.init io.io (λ: <>,
      exception_do (do:  (sync.initialize' #());;;
      do:  (errors.initialize' #());;;
      do:  (ErrShortWrite'init #());;;
      do:  (errInvalidWrite'init #());;;
      do:  (ErrShortBuffer'init #());;;
      do:  (EOF'init #());;;
      do:  (ErrUnexpectedEOF'init #());;;
      do:  (ErrNoProgress'init #());;;
      do:  (errWhence'init #());;;
      do:  (errOffset'init #());;;
      do:  (Discard'init #());;;
      do:  (_'init #());;;
      do:  (blackHolePool'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (ErrClosedPipe'init #()))
      ).

End code.
End io.
